import { z } from 'zod';

export const MESSAGE_PROTOCOL_VERSION = 1 as const;

export const MessageType = {
  TEXT: 1,
  IMAGE: 2,
  FILE: 8,
  AUDIO: 4,
  VIDEO: 5,
  STICKER: 6,
  CALL_SIGNAL: 2001,
  REVOKE: 9001,
  SYSTEM: 9002,
} as const;

const base = {
  version: z.literal(MESSAGE_PROTOCOL_VERSION),
  clientMsgNo: z.uuid(),
  sentAt: z.number().int().nonnegative(),
  replyTo: z.string().min(1).max(128).optional(),
};

const fileId = z.uuid();

export const textMessageSchema = z.object({
  ...base,
  type: z.literal(MessageType.TEXT),
  text: z.string().min(1).max(10_000),
  mentions: z.array(z.uuid()).max(100).optional(),
});

export const imageMessageSchema = z.object({
  ...base,
  type: z.literal(MessageType.IMAGE),
  fileId,
  width: z.number().int().positive().max(20_000),
  height: z.number().int().positive().max(20_000),
  thumbnailFileId: fileId.optional(),
  caption: z.string().max(2_000).optional(),
});

export const fileMessageSchema = z.object({
  ...base,
  type: z.literal(MessageType.FILE),
  fileId,
  name: z.string().min(1).max(255),
  size: z.number().int().positive().max(104_857_600),
  mimeType: z.string().min(1).max(120),
});

export const audioMessageSchema = z.object({
  ...base,
  type: z.literal(MessageType.AUDIO),
  fileId,
  durationMs: z.number().int().positive().max(600_000),
  waveform: z.array(z.number().int().min(0).max(100)).max(100).optional(),
});

export const videoMessageSchema = z.object({
  ...base,
  type: z.literal(MessageType.VIDEO),
  fileId,
  durationMs: z.number().int().positive().max(3_600_000),
  width: z.number().int().positive().max(20_000),
  height: z.number().int().positive().max(20_000),
  thumbnailFileId: fileId,
  caption: z.string().max(2_000).optional(),
});

export const stickerMessageSchema = z.object({
  ...base,
  type: z.literal(MessageType.STICKER),
  packId: z.string().min(1).max(80),
  stickerId: z.string().min(1).max(80),
  fileId: fileId.optional(),
});

export const callSignalMessageSchema = z.object({
  ...base,
  type: z.literal(MessageType.CALL_SIGNAL),
  callId: z.uuid(),
  callType: z.enum(['audio', 'video']),
  action: z.enum(['invite', 'accept', 'reject', 'cancel', 'end']),
  roomName: z.string().min(1).max(120),
});

export const revokeMessageSchema = z.object({
  ...base,
  type: z.literal(MessageType.REVOKE),
  originalClientMsgNo: z.string().min(1).max(128),
  reason: z.string().max(200).optional(),
});

export const systemMessageSchema = z.object({
  ...base,
  type: z.literal(MessageType.SYSTEM),
  event: z.string().min(1).max(100),
  data: z.record(z.string(), z.unknown()).optional(),
});

export const messageSchema = z.discriminatedUnion('type', [
  textMessageSchema,
  imageMessageSchema,
  fileMessageSchema,
  audioMessageSchema,
  videoMessageSchema,
  stickerMessageSchema,
  callSignalMessageSchema,
  revokeMessageSchema,
  systemMessageSchema,
]);

export type ChatMessage = z.infer<typeof messageSchema>;

export const messageProtocolDescriptor = {
  version: MESSAGE_PROTOCOL_VERSION,
  encoding: 'UTF-8 JSON, then Base64 for WuKongIM HTTP API',
  typeField: 'type',
  types: Object.entries(MessageType).map(([name, type]) => ({ name, type })),
  requirements: {
    clientMsgNo: 'UUID generated once by the sender and reused for retries',
    sentAt: 'Unix epoch milliseconds generated by the sender',
    unknownType: 'Persist but render as an unsupported message',
    unknownField: 'Ignore to allow backward-compatible additions',
  },
} as const;
