/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AdminCallPageResponse } from '../models';
// @ts-ignore
import type { AdminDeviceSessionPageResponse } from '../models';
// @ts-ignore
import type { AdminFilePageResponse } from '../models';
// @ts-ignore
import type { AdminGroupMemberPageResponse } from '../models';
// @ts-ignore
import type { AdminGroupPageResponse } from '../models';
// @ts-ignore
import type { AdminGroupResponse } from '../models';
// @ts-ignore
import type { AdminOverviewResponse } from '../models';
// @ts-ignore
import type { AdminReportPageResponse } from '../models';
// @ts-ignore
import type { AdminReportResponse } from '../models';
// @ts-ignore
import type { AdminUserPageResponse } from '../models';
// @ts-ignore
import type { AdminUserResponse } from '../models';
// @ts-ignore
import type { AuditLogPageResponse } from '../models';
// @ts-ignore
import type { DecideReportDto } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { JobRunPageResponse } from '../models';
// @ts-ignore
import type { JobRunResponse } from '../models';
// @ts-ignore
import type { RuntimeSettingsResponseDto } from '../models';
// @ts-ignore
import type { SetGroupPolicyDto } from '../models';
// @ts-ignore
import type { SetUserRoleDto } from '../models';
// @ts-ignore
import type { SuccessResponse } from '../models';
// @ts-ignore
import type { UpdateRuntimeSettingsDto } from '../models';
/**
 * AdminApi - axios parameter creator
 */
export const AdminApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminActivateUser: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('adminActivateUser', 'userId', userId)
            const localVarPath = `/api/v1/admin/users/{userId}/activate`
                .replace('{userId}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} reportId 
         * @param {DecideReportDto} decideReportDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminDecideReport: async (reportId: string, decideReportDto: DecideReportDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'reportId' is not null or undefined
            assertParamExists('adminDecideReport', 'reportId', reportId)
            // verify required parameter 'decideReportDto' is not null or undefined
            assertParamExists('adminDecideReport', 'decideReportDto', decideReportDto)
            const localVarPath = `/api/v1/admin/reports/{reportId}/decision`
                .replace('{reportId}', encodeURIComponent(String(reportId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(decideReportDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminGetGroup: async (groupId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('adminGetGroup', 'groupId', groupId)
            const localVarPath = `/api/v1/admin/groups/{groupId}`
                .replace('{groupId}', encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminGetRuntimeSettings: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admin/runtime-settings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminGetUser: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('adminGetUser', 'userId', userId)
            const localVarPath = `/api/v1/admin/users/{userId}`
                .replace('{userId}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {string} [action] 
         * @param {string} [targetType] 
         * @param {string} [actorUserId] 
         * @param {string} [targetId] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListAuditLogs: async (limit?: number, cursor?: string, action?: string, targetType?: string, actorUserId?: string, targetId?: string, from?: string, to?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admin/audit-logs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (action !== undefined) {
                localVarQueryParameter['action'] = action;
            }

            if (targetType !== undefined) {
                localVarQueryParameter['targetType'] = targetType;
            }

            if (actorUserId !== undefined) {
                localVarQueryParameter['actorUserId'] = actorUserId;
            }

            if (targetId !== undefined) {
                localVarQueryParameter['targetId'] = targetId;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {AdminListCallsTypeEnum} [type] 
         * @param {AdminListCallsStatusEnum} [status] 
         * @param {string} [participant] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListCalls: async (limit?: number, cursor?: string, type?: AdminListCallsTypeEnum, status?: AdminListCallsStatusEnum, participant?: string, from?: string, to?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admin/calls`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (participant !== undefined) {
                localVarQueryParameter['participant'] = participant;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {AdminListFilesStatusEnum} [status] 
         * @param {AdminListFilesScopeEnum} [scope] 
         * @param {string} [search] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListFiles: async (limit?: number, cursor?: string, status?: AdminListFilesStatusEnum, scope?: AdminListFilesScopeEnum, search?: string, from?: string, to?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admin/files`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (scope !== undefined) {
                localVarQueryParameter['scope'] = scope;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListGroupMembers: async (groupId: string, limit?: number, cursor?: string, search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('adminListGroupMembers', 'groupId', groupId)
            const localVarPath = `/api/v1/admin/groups/{groupId}/members`
                .replace('{groupId}', encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [limit] 
         * @param {AdminListGroupsStatusEnum} [status] 
         * @param {string} [cursor] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListGroups: async (limit?: number, status?: AdminListGroupsStatusEnum, cursor?: string, search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admin/groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {AdminListJobRunsStatusEnum} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListJobRuns: async (limit?: number, cursor?: string, status?: AdminListJobRunsStatusEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admin/jobs/runs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {AdminListReportsStatusEnum} [status] 
         * @param {string} [search] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListReports: async (limit?: number, cursor?: string, status?: AdminListReportsStatusEnum, search?: string, from?: string, to?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admin/reports`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} userId 
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListUserDevices: async (userId: string, limit?: number, cursor?: string, search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('adminListUserDevices', 'userId', userId)
            const localVarPath = `/api/v1/admin/users/{userId}/devices`
                .replace('{userId}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [limit] 
         * @param {AdminListUsersStatusEnum} [status] 
         * @param {AdminListUsersRoleEnum} [role] 
         * @param {string} [cursor] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListUsers: async (limit?: number, status?: AdminListUsersStatusEnum, role?: AdminListUsersRoleEnum, cursor?: string, search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admin/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (role !== undefined) {
                localVarQueryParameter['role'] = role;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminOverview: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admin/overview`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} userId 
         * @param {string} sessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminRevokeUserDevice: async (userId: string, sessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('adminRevokeUserDevice', 'userId', userId)
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('adminRevokeUserDevice', 'sessionId', sessionId)
            const localVarPath = `/api/v1/admin/users/{userId}/devices/{sessionId}`
                .replace('{userId}', encodeURIComponent(String(userId)))
                .replace('{sessionId}', encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminRunCleanup: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admin/jobs/cleanup/run`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {SetGroupPolicyDto} setGroupPolicyDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminSetGroupPolicy: async (groupId: string, setGroupPolicyDto: SetGroupPolicyDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('adminSetGroupPolicy', 'groupId', groupId)
            // verify required parameter 'setGroupPolicyDto' is not null or undefined
            assertParamExists('adminSetGroupPolicy', 'setGroupPolicyDto', setGroupPolicyDto)
            const localVarPath = `/api/v1/admin/groups/{groupId}/policy`
                .replace('{groupId}', encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setGroupPolicyDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} userId 
         * @param {SetUserRoleDto} setUserRoleDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminSetUserRole: async (userId: string, setUserRoleDto: SetUserRoleDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('adminSetUserRole', 'userId', userId)
            // verify required parameter 'setUserRoleDto' is not null or undefined
            assertParamExists('adminSetUserRole', 'setUserRoleDto', setUserRoleDto)
            const localVarPath = `/api/v1/admin/users/{userId}/role`
                .replace('{userId}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setUserRoleDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminSuspendUser: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('adminSuspendUser', 'userId', userId)
            const localVarPath = `/api/v1/admin/users/{userId}/suspend`
                .replace('{userId}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateRuntimeSettingsDto} updateRuntimeSettingsDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminUpdateRuntimeSettings: async (updateRuntimeSettingsDto: UpdateRuntimeSettingsDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateRuntimeSettingsDto' is not null or undefined
            assertParamExists('adminUpdateRuntimeSettings', 'updateRuntimeSettingsDto', updateRuntimeSettingsDto)
            const localVarPath = `/api/v1/admin/runtime-settings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateRuntimeSettingsDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminApi - functional programming interface
 */
export const AdminApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminActivateUser(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminActivateUser(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminActivateUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} reportId 
         * @param {DecideReportDto} decideReportDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminDecideReport(reportId: string, decideReportDto: DecideReportDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminReportResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminDecideReport(reportId, decideReportDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminDecideReport']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminGetGroup(groupId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminGroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminGetGroup(groupId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminGetGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminGetRuntimeSettings(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RuntimeSettingsResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminGetRuntimeSettings(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminGetRuntimeSettings']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminGetUser(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminGetUser(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminGetUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {string} [action] 
         * @param {string} [targetType] 
         * @param {string} [actorUserId] 
         * @param {string} [targetId] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminListAuditLogs(limit?: number, cursor?: string, action?: string, targetType?: string, actorUserId?: string, targetId?: string, from?: string, to?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuditLogPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminListAuditLogs(limit, cursor, action, targetType, actorUserId, targetId, from, to, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminListAuditLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {AdminListCallsTypeEnum} [type] 
         * @param {AdminListCallsStatusEnum} [status] 
         * @param {string} [participant] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminListCalls(limit?: number, cursor?: string, type?: AdminListCallsTypeEnum, status?: AdminListCallsStatusEnum, participant?: string, from?: string, to?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminCallPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminListCalls(limit, cursor, type, status, participant, from, to, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminListCalls']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {AdminListFilesStatusEnum} [status] 
         * @param {AdminListFilesScopeEnum} [scope] 
         * @param {string} [search] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminListFiles(limit?: number, cursor?: string, status?: AdminListFilesStatusEnum, scope?: AdminListFilesScopeEnum, search?: string, from?: string, to?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminFilePageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminListFiles(limit, cursor, status, scope, search, from, to, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminListFiles']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminListGroupMembers(groupId: string, limit?: number, cursor?: string, search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminGroupMemberPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminListGroupMembers(groupId, limit, cursor, search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminListGroupMembers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [limit] 
         * @param {AdminListGroupsStatusEnum} [status] 
         * @param {string} [cursor] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminListGroups(limit?: number, status?: AdminListGroupsStatusEnum, cursor?: string, search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminGroupPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminListGroups(limit, status, cursor, search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminListGroups']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {AdminListJobRunsStatusEnum} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminListJobRuns(limit?: number, cursor?: string, status?: AdminListJobRunsStatusEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JobRunPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminListJobRuns(limit, cursor, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminListJobRuns']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {AdminListReportsStatusEnum} [status] 
         * @param {string} [search] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminListReports(limit?: number, cursor?: string, status?: AdminListReportsStatusEnum, search?: string, from?: string, to?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminReportPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminListReports(limit, cursor, status, search, from, to, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminListReports']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} userId 
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminListUserDevices(userId: string, limit?: number, cursor?: string, search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminDeviceSessionPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminListUserDevices(userId, limit, cursor, search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminListUserDevices']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [limit] 
         * @param {AdminListUsersStatusEnum} [status] 
         * @param {AdminListUsersRoleEnum} [role] 
         * @param {string} [cursor] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminListUsers(limit?: number, status?: AdminListUsersStatusEnum, role?: AdminListUsersRoleEnum, cursor?: string, search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminUserPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminListUsers(limit, status, role, cursor, search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminListUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminOverview(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminOverviewResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminOverview(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminOverview']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} userId 
         * @param {string} sessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminRevokeUserDevice(userId: string, sessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminRevokeUserDevice(userId, sessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminRevokeUserDevice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminRunCleanup(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JobRunResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminRunCleanup(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminRunCleanup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {SetGroupPolicyDto} setGroupPolicyDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminSetGroupPolicy(groupId: string, setGroupPolicyDto: SetGroupPolicyDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminGroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminSetGroupPolicy(groupId, setGroupPolicyDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminSetGroupPolicy']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} userId 
         * @param {SetUserRoleDto} setUserRoleDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminSetUserRole(userId: string, setUserRoleDto: SetUserRoleDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminSetUserRole(userId, setUserRoleDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminSetUserRole']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminSuspendUser(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminSuspendUser(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminSuspendUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UpdateRuntimeSettingsDto} updateRuntimeSettingsDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminUpdateRuntimeSettings(updateRuntimeSettingsDto: UpdateRuntimeSettingsDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RuntimeSettingsResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminUpdateRuntimeSettings(updateRuntimeSettingsDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.adminUpdateRuntimeSettings']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminApi - factory interface
 */
export const AdminApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminApiFp(configuration)
    return {
        /**
         * 
         * @param {AdminApiAdminActivateUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminActivateUser(requestParameters: AdminApiAdminActivateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdminUserResponse> {
            return localVarFp.adminActivateUser(requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminDecideReportRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminDecideReport(requestParameters: AdminApiAdminDecideReportRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdminReportResponse> {
            return localVarFp.adminDecideReport(requestParameters.reportId, requestParameters.decideReportDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminGetGroupRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminGetGroup(requestParameters: AdminApiAdminGetGroupRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdminGroupResponse> {
            return localVarFp.adminGetGroup(requestParameters.groupId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminGetRuntimeSettings(options?: RawAxiosRequestConfig): AxiosPromise<RuntimeSettingsResponseDto> {
            return localVarFp.adminGetRuntimeSettings(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminGetUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminGetUser(requestParameters: AdminApiAdminGetUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdminUserResponse> {
            return localVarFp.adminGetUser(requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminListAuditLogsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListAuditLogs(requestParameters: AdminApiAdminListAuditLogsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<AuditLogPageResponse> {
            return localVarFp.adminListAuditLogs(requestParameters.limit, requestParameters.cursor, requestParameters.action, requestParameters.targetType, requestParameters.actorUserId, requestParameters.targetId, requestParameters.from, requestParameters.to, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminListCallsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListCalls(requestParameters: AdminApiAdminListCallsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<AdminCallPageResponse> {
            return localVarFp.adminListCalls(requestParameters.limit, requestParameters.cursor, requestParameters.type, requestParameters.status, requestParameters.participant, requestParameters.from, requestParameters.to, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminListFilesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListFiles(requestParameters: AdminApiAdminListFilesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<AdminFilePageResponse> {
            return localVarFp.adminListFiles(requestParameters.limit, requestParameters.cursor, requestParameters.status, requestParameters.scope, requestParameters.search, requestParameters.from, requestParameters.to, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminListGroupMembersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListGroupMembers(requestParameters: AdminApiAdminListGroupMembersRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdminGroupMemberPageResponse> {
            return localVarFp.adminListGroupMembers(requestParameters.groupId, requestParameters.limit, requestParameters.cursor, requestParameters.search, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminListGroupsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListGroups(requestParameters: AdminApiAdminListGroupsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<AdminGroupPageResponse> {
            return localVarFp.adminListGroups(requestParameters.limit, requestParameters.status, requestParameters.cursor, requestParameters.search, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminListJobRunsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListJobRuns(requestParameters: AdminApiAdminListJobRunsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<JobRunPageResponse> {
            return localVarFp.adminListJobRuns(requestParameters.limit, requestParameters.cursor, requestParameters.status, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminListReportsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListReports(requestParameters: AdminApiAdminListReportsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<AdminReportPageResponse> {
            return localVarFp.adminListReports(requestParameters.limit, requestParameters.cursor, requestParameters.status, requestParameters.search, requestParameters.from, requestParameters.to, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminListUserDevicesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListUserDevices(requestParameters: AdminApiAdminListUserDevicesRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdminDeviceSessionPageResponse> {
            return localVarFp.adminListUserDevices(requestParameters.userId, requestParameters.limit, requestParameters.cursor, requestParameters.search, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminListUsersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminListUsers(requestParameters: AdminApiAdminListUsersRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<AdminUserPageResponse> {
            return localVarFp.adminListUsers(requestParameters.limit, requestParameters.status, requestParameters.role, requestParameters.cursor, requestParameters.search, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminOverview(options?: RawAxiosRequestConfig): AxiosPromise<AdminOverviewResponse> {
            return localVarFp.adminOverview(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminRevokeUserDeviceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminRevokeUserDevice(requestParameters: AdminApiAdminRevokeUserDeviceRequest, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.adminRevokeUserDevice(requestParameters.userId, requestParameters.sessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminRunCleanup(options?: RawAxiosRequestConfig): AxiosPromise<JobRunResponse> {
            return localVarFp.adminRunCleanup(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminSetGroupPolicyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminSetGroupPolicy(requestParameters: AdminApiAdminSetGroupPolicyRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdminGroupResponse> {
            return localVarFp.adminSetGroupPolicy(requestParameters.groupId, requestParameters.setGroupPolicyDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminSetUserRoleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminSetUserRole(requestParameters: AdminApiAdminSetUserRoleRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdminUserResponse> {
            return localVarFp.adminSetUserRole(requestParameters.userId, requestParameters.setUserRoleDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminSuspendUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminSuspendUser(requestParameters: AdminApiAdminSuspendUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdminUserResponse> {
            return localVarFp.adminSuspendUser(requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AdminApiAdminUpdateRuntimeSettingsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminUpdateRuntimeSettings(requestParameters: AdminApiAdminUpdateRuntimeSettingsRequest, options?: RawAxiosRequestConfig): AxiosPromise<RuntimeSettingsResponseDto> {
            return localVarFp.adminUpdateRuntimeSettings(requestParameters.updateRuntimeSettingsDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for adminActivateUser operation in AdminApi.
 */
export interface AdminApiAdminActivateUserRequest {
    readonly userId: string
}

/**
 * Request parameters for adminDecideReport operation in AdminApi.
 */
export interface AdminApiAdminDecideReportRequest {
    readonly reportId: string

    readonly decideReportDto: DecideReportDto
}

/**
 * Request parameters for adminGetGroup operation in AdminApi.
 */
export interface AdminApiAdminGetGroupRequest {
    readonly groupId: string
}

/**
 * Request parameters for adminGetUser operation in AdminApi.
 */
export interface AdminApiAdminGetUserRequest {
    readonly userId: string
}

/**
 * Request parameters for adminListAuditLogs operation in AdminApi.
 */
export interface AdminApiAdminListAuditLogsRequest {
    readonly limit?: number

    readonly cursor?: string

    readonly action?: string

    readonly targetType?: string

    readonly actorUserId?: string

    readonly targetId?: string

    readonly from?: string

    readonly to?: string
}

/**
 * Request parameters for adminListCalls operation in AdminApi.
 */
export interface AdminApiAdminListCallsRequest {
    readonly limit?: number

    readonly cursor?: string

    readonly type?: AdminListCallsTypeEnum

    readonly status?: AdminListCallsStatusEnum

    readonly participant?: string

    readonly from?: string

    readonly to?: string
}

/**
 * Request parameters for adminListFiles operation in AdminApi.
 */
export interface AdminApiAdminListFilesRequest {
    readonly limit?: number

    readonly cursor?: string

    readonly status?: AdminListFilesStatusEnum

    readonly scope?: AdminListFilesScopeEnum

    readonly search?: string

    readonly from?: string

    readonly to?: string
}

/**
 * Request parameters for adminListGroupMembers operation in AdminApi.
 */
export interface AdminApiAdminListGroupMembersRequest {
    readonly groupId: string

    readonly limit?: number

    readonly cursor?: string

    readonly search?: string
}

/**
 * Request parameters for adminListGroups operation in AdminApi.
 */
export interface AdminApiAdminListGroupsRequest {
    readonly limit?: number

    readonly status?: AdminListGroupsStatusEnum

    readonly cursor?: string

    readonly search?: string
}

/**
 * Request parameters for adminListJobRuns operation in AdminApi.
 */
export interface AdminApiAdminListJobRunsRequest {
    readonly limit?: number

    readonly cursor?: string

    readonly status?: AdminListJobRunsStatusEnum
}

/**
 * Request parameters for adminListReports operation in AdminApi.
 */
export interface AdminApiAdminListReportsRequest {
    readonly limit?: number

    readonly cursor?: string

    readonly status?: AdminListReportsStatusEnum

    readonly search?: string

    readonly from?: string

    readonly to?: string
}

/**
 * Request parameters for adminListUserDevices operation in AdminApi.
 */
export interface AdminApiAdminListUserDevicesRequest {
    readonly userId: string

    readonly limit?: number

    readonly cursor?: string

    readonly search?: string
}

/**
 * Request parameters for adminListUsers operation in AdminApi.
 */
export interface AdminApiAdminListUsersRequest {
    readonly limit?: number

    readonly status?: AdminListUsersStatusEnum

    readonly role?: AdminListUsersRoleEnum

    readonly cursor?: string

    readonly search?: string
}

/**
 * Request parameters for adminRevokeUserDevice operation in AdminApi.
 */
export interface AdminApiAdminRevokeUserDeviceRequest {
    readonly userId: string

    readonly sessionId: string
}

/**
 * Request parameters for adminSetGroupPolicy operation in AdminApi.
 */
export interface AdminApiAdminSetGroupPolicyRequest {
    readonly groupId: string

    readonly setGroupPolicyDto: SetGroupPolicyDto
}

/**
 * Request parameters for adminSetUserRole operation in AdminApi.
 */
export interface AdminApiAdminSetUserRoleRequest {
    readonly userId: string

    readonly setUserRoleDto: SetUserRoleDto
}

/**
 * Request parameters for adminSuspendUser operation in AdminApi.
 */
export interface AdminApiAdminSuspendUserRequest {
    readonly userId: string
}

/**
 * Request parameters for adminUpdateRuntimeSettings operation in AdminApi.
 */
export interface AdminApiAdminUpdateRuntimeSettingsRequest {
    readonly updateRuntimeSettingsDto: UpdateRuntimeSettingsDto
}

/**
 * AdminApi - object-oriented interface
 */
export class AdminApi extends BaseAPI {
    /**
     * 
     * @param {AdminApiAdminActivateUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminActivateUser(requestParameters: AdminApiAdminActivateUserRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminActivateUser(requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminDecideReportRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminDecideReport(requestParameters: AdminApiAdminDecideReportRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminDecideReport(requestParameters.reportId, requestParameters.decideReportDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminGetGroupRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminGetGroup(requestParameters: AdminApiAdminGetGroupRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminGetGroup(requestParameters.groupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminGetRuntimeSettings(options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminGetRuntimeSettings(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminGetUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminGetUser(requestParameters: AdminApiAdminGetUserRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminGetUser(requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminListAuditLogsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminListAuditLogs(requestParameters: AdminApiAdminListAuditLogsRequest = {}, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminListAuditLogs(requestParameters.limit, requestParameters.cursor, requestParameters.action, requestParameters.targetType, requestParameters.actorUserId, requestParameters.targetId, requestParameters.from, requestParameters.to, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminListCallsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminListCalls(requestParameters: AdminApiAdminListCallsRequest = {}, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminListCalls(requestParameters.limit, requestParameters.cursor, requestParameters.type, requestParameters.status, requestParameters.participant, requestParameters.from, requestParameters.to, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminListFilesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminListFiles(requestParameters: AdminApiAdminListFilesRequest = {}, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminListFiles(requestParameters.limit, requestParameters.cursor, requestParameters.status, requestParameters.scope, requestParameters.search, requestParameters.from, requestParameters.to, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminListGroupMembersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminListGroupMembers(requestParameters: AdminApiAdminListGroupMembersRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminListGroupMembers(requestParameters.groupId, requestParameters.limit, requestParameters.cursor, requestParameters.search, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminListGroupsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminListGroups(requestParameters: AdminApiAdminListGroupsRequest = {}, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminListGroups(requestParameters.limit, requestParameters.status, requestParameters.cursor, requestParameters.search, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminListJobRunsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminListJobRuns(requestParameters: AdminApiAdminListJobRunsRequest = {}, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminListJobRuns(requestParameters.limit, requestParameters.cursor, requestParameters.status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminListReportsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminListReports(requestParameters: AdminApiAdminListReportsRequest = {}, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminListReports(requestParameters.limit, requestParameters.cursor, requestParameters.status, requestParameters.search, requestParameters.from, requestParameters.to, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminListUserDevicesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminListUserDevices(requestParameters: AdminApiAdminListUserDevicesRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminListUserDevices(requestParameters.userId, requestParameters.limit, requestParameters.cursor, requestParameters.search, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminListUsersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminListUsers(requestParameters: AdminApiAdminListUsersRequest = {}, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminListUsers(requestParameters.limit, requestParameters.status, requestParameters.role, requestParameters.cursor, requestParameters.search, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminOverview(options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminOverview(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminRevokeUserDeviceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminRevokeUserDevice(requestParameters: AdminApiAdminRevokeUserDeviceRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminRevokeUserDevice(requestParameters.userId, requestParameters.sessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminRunCleanup(options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminRunCleanup(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminSetGroupPolicyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminSetGroupPolicy(requestParameters: AdminApiAdminSetGroupPolicyRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminSetGroupPolicy(requestParameters.groupId, requestParameters.setGroupPolicyDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminSetUserRoleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminSetUserRole(requestParameters: AdminApiAdminSetUserRoleRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminSetUserRole(requestParameters.userId, requestParameters.setUserRoleDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminSuspendUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminSuspendUser(requestParameters: AdminApiAdminSuspendUserRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminSuspendUser(requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AdminApiAdminUpdateRuntimeSettingsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminUpdateRuntimeSettings(requestParameters: AdminApiAdminUpdateRuntimeSettingsRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).adminUpdateRuntimeSettings(requestParameters.updateRuntimeSettingsDto, options).then((request) => request(this.axios, this.basePath));
    }
}

export enum AdminListCallsTypeEnum {
    Audio = 'AUDIO',
    Video = 'VIDEO'
}
export enum AdminListCallsStatusEnum {
    Rejected = 'REJECTED',
    Failed = 'FAILED',
    Accepted = 'ACCEPTED',
    Cancelled = 'CANCELLED',
    Missed = 'MISSED',
    Ended = 'ENDED',
    Inviting = 'INVITING',
    Ringing = 'RINGING',
    Connected = 'CONNECTED'
}
export enum AdminListFilesStatusEnum {
    Pending = 'PENDING',
    Uploaded = 'UPLOADED',
    Ready = 'READY',
    Rejected = 'REJECTED',
    DeletePending = 'DELETE_PENDING',
    Deleted = 'DELETED'
}
export enum AdminListFilesScopeEnum {
    Private = 'PRIVATE',
    Direct = 'DIRECT',
    Group = 'GROUP'
}
export enum AdminListGroupsStatusEnum {
    Active = 'ACTIVE',
    Suspended = 'SUSPENDED',
    Disbanded = 'DISBANDED'
}
export enum AdminListJobRunsStatusEnum {
    Failed = 'FAILED',
    Running = 'RUNNING',
    Success = 'SUCCESS',
    Skipped = 'SKIPPED'
}
export enum AdminListReportsStatusEnum {
    Pending = 'PENDING',
    Resolved = 'RESOLVED',
    Dismissed = 'DISMISSED'
}
export enum AdminListUsersStatusEnum {
    Deleted = 'DELETED',
    Active = 'ACTIVE',
    Suspended = 'SUSPENDED'
}
export enum AdminListUsersRoleEnum {
    User = 'USER',
    Admin = 'ADMIN'
}
