/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CallSessionResponse } from '../models';
// @ts-ignore
import type { CreateCallDto } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { LiveKitTokenResponse } from '../models';
/**
 * CallsApi - axios parameter creator
 */
export const CallsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} callId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsAccept: async (callId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'callId' is not null or undefined
            assertParamExists('callsAccept', 'callId', callId)
            const localVarPath = `/api/v1/calls/{callId}/accept`
                .replace('{callId}', encodeURIComponent(String(callId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} callId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsBusy: async (callId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'callId' is not null or undefined
            assertParamExists('callsBusy', 'callId', callId)
            const localVarPath = `/api/v1/calls/{callId}/busy`
                .replace('{callId}', encodeURIComponent(String(callId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} callId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsCancel: async (callId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'callId' is not null or undefined
            assertParamExists('callsCancel', 'callId', callId)
            const localVarPath = `/api/v1/calls/{callId}/cancel`
                .replace('{callId}', encodeURIComponent(String(callId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreateCallDto} createCallDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsCreate: async (createCallDto: CreateCallDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createCallDto' is not null or undefined
            assertParamExists('callsCreate', 'createCallDto', createCallDto)
            const localVarPath = `/api/v1/calls`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCallDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} callId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsCreateToken: async (callId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'callId' is not null or undefined
            assertParamExists('callsCreateToken', 'callId', callId)
            const localVarPath = `/api/v1/calls/{callId}/token`
                .replace('{callId}', encodeURIComponent(String(callId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} callId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsEnd: async (callId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'callId' is not null or undefined
            assertParamExists('callsEnd', 'callId', callId)
            const localVarPath = `/api/v1/calls/{callId}/end`
                .replace('{callId}', encodeURIComponent(String(callId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/calls`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} callId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsMiss: async (callId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'callId' is not null or undefined
            assertParamExists('callsMiss', 'callId', callId)
            const localVarPath = `/api/v1/calls/{callId}/miss`
                .replace('{callId}', encodeURIComponent(String(callId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} callId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsReject: async (callId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'callId' is not null or undefined
            assertParamExists('callsReject', 'callId', callId)
            const localVarPath = `/api/v1/calls/{callId}/reject`
                .replace('{callId}', encodeURIComponent(String(callId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CallsApi - functional programming interface
 */
export const CallsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CallsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} callId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async callsAccept(callId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CallSessionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.callsAccept(callId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CallsApi.callsAccept']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} callId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async callsBusy(callId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.callsBusy(callId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CallsApi.callsBusy']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} callId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async callsCancel(callId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CallSessionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.callsCancel(callId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CallsApi.callsCancel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CreateCallDto} createCallDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async callsCreate(createCallDto: CreateCallDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CallSessionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.callsCreate(createCallDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CallsApi.callsCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} callId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async callsCreateToken(callId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LiveKitTokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.callsCreateToken(callId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CallsApi.callsCreateToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} callId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async callsEnd(callId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CallSessionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.callsEnd(callId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CallsApi.callsEnd']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async callsList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.callsList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CallsApi.callsList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} callId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async callsMiss(callId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.callsMiss(callId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CallsApi.callsMiss']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} callId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async callsReject(callId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CallSessionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.callsReject(callId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CallsApi.callsReject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CallsApi - factory interface
 */
export const CallsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CallsApiFp(configuration)
    return {
        /**
         * 
         * @param {CallsApiCallsAcceptRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsAccept(requestParameters: CallsApiCallsAcceptRequest, options?: RawAxiosRequestConfig): AxiosPromise<CallSessionResponse> {
            return localVarFp.callsAccept(requestParameters.callId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CallsApiCallsBusyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsBusy(requestParameters: CallsApiCallsBusyRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.callsBusy(requestParameters.callId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CallsApiCallsCancelRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsCancel(requestParameters: CallsApiCallsCancelRequest, options?: RawAxiosRequestConfig): AxiosPromise<CallSessionResponse> {
            return localVarFp.callsCancel(requestParameters.callId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CallsApiCallsCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsCreate(requestParameters: CallsApiCallsCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<CallSessionResponse> {
            return localVarFp.callsCreate(requestParameters.createCallDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CallsApiCallsCreateTokenRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsCreateToken(requestParameters: CallsApiCallsCreateTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<LiveKitTokenResponse> {
            return localVarFp.callsCreateToken(requestParameters.callId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CallsApiCallsEndRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsEnd(requestParameters: CallsApiCallsEndRequest, options?: RawAxiosRequestConfig): AxiosPromise<CallSessionResponse> {
            return localVarFp.callsEnd(requestParameters.callId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsList(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.callsList(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CallsApiCallsMissRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsMiss(requestParameters: CallsApiCallsMissRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.callsMiss(requestParameters.callId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CallsApiCallsRejectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callsReject(requestParameters: CallsApiCallsRejectRequest, options?: RawAxiosRequestConfig): AxiosPromise<CallSessionResponse> {
            return localVarFp.callsReject(requestParameters.callId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for callsAccept operation in CallsApi.
 */
export interface CallsApiCallsAcceptRequest {
    readonly callId: string
}

/**
 * Request parameters for callsBusy operation in CallsApi.
 */
export interface CallsApiCallsBusyRequest {
    readonly callId: string
}

/**
 * Request parameters for callsCancel operation in CallsApi.
 */
export interface CallsApiCallsCancelRequest {
    readonly callId: string
}

/**
 * Request parameters for callsCreate operation in CallsApi.
 */
export interface CallsApiCallsCreateRequest {
    readonly createCallDto: CreateCallDto
}

/**
 * Request parameters for callsCreateToken operation in CallsApi.
 */
export interface CallsApiCallsCreateTokenRequest {
    readonly callId: string
}

/**
 * Request parameters for callsEnd operation in CallsApi.
 */
export interface CallsApiCallsEndRequest {
    readonly callId: string
}

/**
 * Request parameters for callsMiss operation in CallsApi.
 */
export interface CallsApiCallsMissRequest {
    readonly callId: string
}

/**
 * Request parameters for callsReject operation in CallsApi.
 */
export interface CallsApiCallsRejectRequest {
    readonly callId: string
}

/**
 * CallsApi - object-oriented interface
 */
export class CallsApi extends BaseAPI {
    /**
     * 
     * @param {CallsApiCallsAcceptRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public callsAccept(requestParameters: CallsApiCallsAcceptRequest, options?: RawAxiosRequestConfig) {
        return CallsApiFp(this.configuration).callsAccept(requestParameters.callId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CallsApiCallsBusyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public callsBusy(requestParameters: CallsApiCallsBusyRequest, options?: RawAxiosRequestConfig) {
        return CallsApiFp(this.configuration).callsBusy(requestParameters.callId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CallsApiCallsCancelRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public callsCancel(requestParameters: CallsApiCallsCancelRequest, options?: RawAxiosRequestConfig) {
        return CallsApiFp(this.configuration).callsCancel(requestParameters.callId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CallsApiCallsCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public callsCreate(requestParameters: CallsApiCallsCreateRequest, options?: RawAxiosRequestConfig) {
        return CallsApiFp(this.configuration).callsCreate(requestParameters.createCallDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CallsApiCallsCreateTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public callsCreateToken(requestParameters: CallsApiCallsCreateTokenRequest, options?: RawAxiosRequestConfig) {
        return CallsApiFp(this.configuration).callsCreateToken(requestParameters.callId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CallsApiCallsEndRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public callsEnd(requestParameters: CallsApiCallsEndRequest, options?: RawAxiosRequestConfig) {
        return CallsApiFp(this.configuration).callsEnd(requestParameters.callId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public callsList(options?: RawAxiosRequestConfig) {
        return CallsApiFp(this.configuration).callsList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CallsApiCallsMissRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public callsMiss(requestParameters: CallsApiCallsMissRequest, options?: RawAxiosRequestConfig) {
        return CallsApiFp(this.configuration).callsMiss(requestParameters.callId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CallsApiCallsRejectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public callsReject(requestParameters: CallsApiCallsRejectRequest, options?: RawAxiosRequestConfig) {
        return CallsApiFp(this.configuration).callsReject(requestParameters.callId, options).then((request) => request(this.axios, this.basePath));
    }
}

