/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddGroupMembersDto } from '../models';
// @ts-ignore
import type { CountResponse } from '../models';
// @ts-ignore
import type { CreateGroupDto } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { GroupJoinMessageDto } from '../models';
// @ts-ignore
import type { GroupJoinRequestResponse } from '../models';
// @ts-ignore
import type { GroupMemberResponse } from '../models';
// @ts-ignore
import type { GroupResponse } from '../models';
// @ts-ignore
import type { InviteGroupMemberDto } from '../models';
// @ts-ignore
import type { MuteMemberDto } from '../models';
// @ts-ignore
import type { SetGroupAvatarDto } from '../models';
// @ts-ignore
import type { SetMemberRoleDto } from '../models';
// @ts-ignore
import type { SuccessResponse } from '../models';
// @ts-ignore
import type { TransferOwnerDto } from '../models';
// @ts-ignore
import type { UpdateGroupDto } from '../models';
/**
 * GroupsApi - axios parameter creator
 */
export const GroupsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} groupId 
         * @param {AddGroupMembersDto} addGroupMembersDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsAddMembers: async (groupId: string, addGroupMembersDto: AddGroupMembersDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('groupsAddMembers', 'groupId', groupId)
            // verify required parameter 'addGroupMembersDto' is not null or undefined
            assertParamExists('groupsAddMembers', 'addGroupMembersDto', addGroupMembersDto)
            const localVarPath = `/api/v1/groups/{groupId}/members`
                .replace('{groupId}', encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addGroupMembersDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {GroupJoinMessageDto} groupJoinMessageDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsApplyToJoin: async (groupId: string, groupJoinMessageDto: GroupJoinMessageDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('groupsApplyToJoin', 'groupId', groupId)
            // verify required parameter 'groupJoinMessageDto' is not null or undefined
            assertParamExists('groupsApplyToJoin', 'groupJoinMessageDto', groupJoinMessageDto)
            const localVarPath = `/api/v1/groups/{groupId}/join-requests`
                .replace('{groupId}', encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(groupJoinMessageDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} requestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsApproveJoinRequest: async (requestId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestId' is not null or undefined
            assertParamExists('groupsApproveJoinRequest', 'requestId', requestId)
            const localVarPath = `/api/v1/groups/join-requests/{requestId}/approve`
                .replace('{requestId}', encodeURIComponent(String(requestId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} requestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsCancelJoinRequest: async (requestId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestId' is not null or undefined
            assertParamExists('groupsCancelJoinRequest', 'requestId', requestId)
            const localVarPath = `/api/v1/groups/join-requests/{requestId}/cancel`
                .replace('{requestId}', encodeURIComponent(String(requestId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreateGroupDto} createGroupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsCreate: async (createGroupDto: CreateGroupDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createGroupDto' is not null or undefined
            assertParamExists('groupsCreate', 'createGroupDto', createGroupDto)
            const localVarPath = `/api/v1/groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createGroupDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsDisband: async (groupId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('groupsDisband', 'groupId', groupId)
            const localVarPath = `/api/v1/groups/{groupId}`
                .replace('{groupId}', encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsGet: async (groupId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('groupsGet', 'groupId', groupId)
            const localVarPath = `/api/v1/groups/{groupId}`
                .replace('{groupId}', encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {InviteGroupMemberDto} inviteGroupMemberDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsInviteMember: async (groupId: string, inviteGroupMemberDto: InviteGroupMemberDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('groupsInviteMember', 'groupId', groupId)
            // verify required parameter 'inviteGroupMemberDto' is not null or undefined
            assertParamExists('groupsInviteMember', 'inviteGroupMemberDto', inviteGroupMemberDto)
            const localVarPath = `/api/v1/groups/{groupId}/invitations`
                .replace('{groupId}', encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(inviteGroupMemberDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsLeave: async (groupId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('groupsLeave', 'groupId', groupId)
            const localVarPath = `/api/v1/groups/{groupId}/leave`
                .replace('{groupId}', encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [before] 
         * @param {string} [beforeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsListActionableJoinRequests: async (before?: string, beforeId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/groups/join-requests/actionable`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (before !== undefined) {
                localVarQueryParameter['before'] = before;
            }

            if (beforeId !== undefined) {
                localVarQueryParameter['beforeId'] = beforeId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [before] 
         * @param {string} [beforeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsListMyJoinRequests: async (before?: string, beforeId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/groups/join-requests/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (before !== undefined) {
                localVarQueryParameter['before'] = before;
            }

            if (beforeId !== undefined) {
                localVarQueryParameter['beforeId'] = beforeId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsListPendingJoinRequests: async (groupId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('groupsListPendingJoinRequests', 'groupId', groupId)
            const localVarPath = `/api/v1/groups/{groupId}/join-requests`
                .replace('{groupId}', encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {string} memberId 
         * @param {MuteMemberDto} muteMemberDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsMuteMember: async (groupId: string, memberId: string, muteMemberDto: MuteMemberDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('groupsMuteMember', 'groupId', groupId)
            // verify required parameter 'memberId' is not null or undefined
            assertParamExists('groupsMuteMember', 'memberId', memberId)
            // verify required parameter 'muteMemberDto' is not null or undefined
            assertParamExists('groupsMuteMember', 'muteMemberDto', muteMemberDto)
            const localVarPath = `/api/v1/groups/{groupId}/members/{memberId}/mute`
                .replace('{groupId}', encodeURIComponent(String(groupId)))
                .replace('{memberId}', encodeURIComponent(String(memberId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(muteMemberDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsPendingJoinRequestCount: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/groups/join-requests/pending-count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} requestId 
         * @param {GroupJoinMessageDto} groupJoinMessageDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsRejectJoinRequest: async (requestId: string, groupJoinMessageDto: GroupJoinMessageDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestId' is not null or undefined
            assertParamExists('groupsRejectJoinRequest', 'requestId', requestId)
            // verify required parameter 'groupJoinMessageDto' is not null or undefined
            assertParamExists('groupsRejectJoinRequest', 'groupJoinMessageDto', groupJoinMessageDto)
            const localVarPath = `/api/v1/groups/join-requests/{requestId}/reject`
                .replace('{requestId}', encodeURIComponent(String(requestId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(groupJoinMessageDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsRemoveAvatar: async (groupId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('groupsRemoveAvatar', 'groupId', groupId)
            const localVarPath = `/api/v1/groups/{groupId}/avatar`
                .replace('{groupId}', encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {string} memberId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsRemoveMember: async (groupId: string, memberId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('groupsRemoveMember', 'groupId', groupId)
            // verify required parameter 'memberId' is not null or undefined
            assertParamExists('groupsRemoveMember', 'memberId', memberId)
            const localVarPath = `/api/v1/groups/{groupId}/members/{memberId}`
                .replace('{groupId}', encodeURIComponent(String(groupId)))
                .replace('{memberId}', encodeURIComponent(String(memberId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {SetGroupAvatarDto} setGroupAvatarDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsSetAvatar: async (groupId: string, setGroupAvatarDto: SetGroupAvatarDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('groupsSetAvatar', 'groupId', groupId)
            // verify required parameter 'setGroupAvatarDto' is not null or undefined
            assertParamExists('groupsSetAvatar', 'setGroupAvatarDto', setGroupAvatarDto)
            const localVarPath = `/api/v1/groups/{groupId}/avatar`
                .replace('{groupId}', encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setGroupAvatarDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {string} memberId 
         * @param {SetMemberRoleDto} setMemberRoleDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsSetMemberRole: async (groupId: string, memberId: string, setMemberRoleDto: SetMemberRoleDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('groupsSetMemberRole', 'groupId', groupId)
            // verify required parameter 'memberId' is not null or undefined
            assertParamExists('groupsSetMemberRole', 'memberId', memberId)
            // verify required parameter 'setMemberRoleDto' is not null or undefined
            assertParamExists('groupsSetMemberRole', 'setMemberRoleDto', setMemberRoleDto)
            const localVarPath = `/api/v1/groups/{groupId}/members/{memberId}/role`
                .replace('{groupId}', encodeURIComponent(String(groupId)))
                .replace('{memberId}', encodeURIComponent(String(memberId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setMemberRoleDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {TransferOwnerDto} transferOwnerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsTransferOwner: async (groupId: string, transferOwnerDto: TransferOwnerDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('groupsTransferOwner', 'groupId', groupId)
            // verify required parameter 'transferOwnerDto' is not null or undefined
            assertParamExists('groupsTransferOwner', 'transferOwnerDto', transferOwnerDto)
            const localVarPath = `/api/v1/groups/{groupId}/transfer-owner`
                .replace('{groupId}', encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(transferOwnerDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} groupId 
         * @param {UpdateGroupDto} updateGroupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsUpdate: async (groupId: string, updateGroupDto: UpdateGroupDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('groupsUpdate', 'groupId', groupId)
            // verify required parameter 'updateGroupDto' is not null or undefined
            assertParamExists('groupsUpdate', 'updateGroupDto', updateGroupDto)
            const localVarPath = `/api/v1/groups/{groupId}`
                .replace('{groupId}', encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateGroupDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GroupsApi - functional programming interface
 */
export const GroupsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GroupsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} groupId 
         * @param {AddGroupMembersDto} addGroupMembersDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsAddMembers(groupId: string, addGroupMembersDto: AddGroupMembersDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsAddMembers(groupId, addGroupMembersDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsAddMembers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {GroupJoinMessageDto} groupJoinMessageDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsApplyToJoin(groupId: string, groupJoinMessageDto: GroupJoinMessageDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupJoinRequestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsApplyToJoin(groupId, groupJoinMessageDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsApplyToJoin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} requestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsApproveJoinRequest(requestId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupJoinRequestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsApproveJoinRequest(requestId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsApproveJoinRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} requestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsCancelJoinRequest(requestId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupJoinRequestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsCancelJoinRequest(requestId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsCancelJoinRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CreateGroupDto} createGroupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsCreate(createGroupDto: CreateGroupDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsCreate(createGroupDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsDisband(groupId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsDisband(groupId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsDisband']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsGet(groupId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsGet(groupId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {InviteGroupMemberDto} inviteGroupMemberDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsInviteMember(groupId: string, inviteGroupMemberDto: InviteGroupMemberDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupJoinRequestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsInviteMember(groupId, inviteGroupMemberDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsInviteMember']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsLeave(groupId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsLeave(groupId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsLeave']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GroupResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [before] 
         * @param {string} [beforeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsListActionableJoinRequests(before?: string, beforeId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GroupJoinRequestResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsListActionableJoinRequests(before, beforeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsListActionableJoinRequests']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [before] 
         * @param {string} [beforeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsListMyJoinRequests(before?: string, beforeId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GroupJoinRequestResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsListMyJoinRequests(before, beforeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsListMyJoinRequests']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsListPendingJoinRequests(groupId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GroupJoinRequestResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsListPendingJoinRequests(groupId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsListPendingJoinRequests']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {string} memberId 
         * @param {MuteMemberDto} muteMemberDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsMuteMember(groupId: string, memberId: string, muteMemberDto: MuteMemberDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupMemberResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsMuteMember(groupId, memberId, muteMemberDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsMuteMember']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsPendingJoinRequestCount(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CountResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsPendingJoinRequestCount(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsPendingJoinRequestCount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} requestId 
         * @param {GroupJoinMessageDto} groupJoinMessageDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsRejectJoinRequest(requestId: string, groupJoinMessageDto: GroupJoinMessageDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupJoinRequestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsRejectJoinRequest(requestId, groupJoinMessageDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsRejectJoinRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsRemoveAvatar(groupId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsRemoveAvatar(groupId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsRemoveAvatar']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {string} memberId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsRemoveMember(groupId: string, memberId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsRemoveMember(groupId, memberId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsRemoveMember']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {SetGroupAvatarDto} setGroupAvatarDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsSetAvatar(groupId: string, setGroupAvatarDto: SetGroupAvatarDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsSetAvatar(groupId, setGroupAvatarDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsSetAvatar']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {string} memberId 
         * @param {SetMemberRoleDto} setMemberRoleDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsSetMemberRole(groupId: string, memberId: string, setMemberRoleDto: SetMemberRoleDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupMemberResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsSetMemberRole(groupId, memberId, setMemberRoleDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsSetMemberRole']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {TransferOwnerDto} transferOwnerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsTransferOwner(groupId: string, transferOwnerDto: TransferOwnerDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsTransferOwner(groupId, transferOwnerDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsTransferOwner']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} groupId 
         * @param {UpdateGroupDto} updateGroupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async groupsUpdate(groupId: string, updateGroupDto: UpdateGroupDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.groupsUpdate(groupId, updateGroupDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.groupsUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GroupsApi - factory interface
 */
export const GroupsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GroupsApiFp(configuration)
    return {
        /**
         * 
         * @param {GroupsApiGroupsAddMembersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsAddMembers(requestParameters: GroupsApiGroupsAddMembersRequest, options?: RawAxiosRequestConfig): AxiosPromise<GroupResponse> {
            return localVarFp.groupsAddMembers(requestParameters.groupId, requestParameters.addGroupMembersDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsApplyToJoinRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsApplyToJoin(requestParameters: GroupsApiGroupsApplyToJoinRequest, options?: RawAxiosRequestConfig): AxiosPromise<GroupJoinRequestResponse> {
            return localVarFp.groupsApplyToJoin(requestParameters.groupId, requestParameters.groupJoinMessageDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsApproveJoinRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsApproveJoinRequest(requestParameters: GroupsApiGroupsApproveJoinRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<GroupJoinRequestResponse> {
            return localVarFp.groupsApproveJoinRequest(requestParameters.requestId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsCancelJoinRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsCancelJoinRequest(requestParameters: GroupsApiGroupsCancelJoinRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<GroupJoinRequestResponse> {
            return localVarFp.groupsCancelJoinRequest(requestParameters.requestId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsCreate(requestParameters: GroupsApiGroupsCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<GroupResponse> {
            return localVarFp.groupsCreate(requestParameters.createGroupDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsDisbandRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsDisband(requestParameters: GroupsApiGroupsDisbandRequest, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.groupsDisband(requestParameters.groupId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsGet(requestParameters: GroupsApiGroupsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<GroupResponse> {
            return localVarFp.groupsGet(requestParameters.groupId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsInviteMemberRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsInviteMember(requestParameters: GroupsApiGroupsInviteMemberRequest, options?: RawAxiosRequestConfig): AxiosPromise<GroupJoinRequestResponse> {
            return localVarFp.groupsInviteMember(requestParameters.groupId, requestParameters.inviteGroupMemberDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsLeaveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsLeave(requestParameters: GroupsApiGroupsLeaveRequest, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.groupsLeave(requestParameters.groupId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsList(options?: RawAxiosRequestConfig): AxiosPromise<Array<GroupResponse>> {
            return localVarFp.groupsList(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsListActionableJoinRequestsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsListActionableJoinRequests(requestParameters: GroupsApiGroupsListActionableJoinRequestsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<GroupJoinRequestResponse>> {
            return localVarFp.groupsListActionableJoinRequests(requestParameters.before, requestParameters.beforeId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsListMyJoinRequestsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsListMyJoinRequests(requestParameters: GroupsApiGroupsListMyJoinRequestsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<GroupJoinRequestResponse>> {
            return localVarFp.groupsListMyJoinRequests(requestParameters.before, requestParameters.beforeId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsListPendingJoinRequestsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsListPendingJoinRequests(requestParameters: GroupsApiGroupsListPendingJoinRequestsRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<GroupJoinRequestResponse>> {
            return localVarFp.groupsListPendingJoinRequests(requestParameters.groupId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsMuteMemberRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsMuteMember(requestParameters: GroupsApiGroupsMuteMemberRequest, options?: RawAxiosRequestConfig): AxiosPromise<GroupMemberResponse> {
            return localVarFp.groupsMuteMember(requestParameters.groupId, requestParameters.memberId, requestParameters.muteMemberDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsPendingJoinRequestCount(options?: RawAxiosRequestConfig): AxiosPromise<CountResponse> {
            return localVarFp.groupsPendingJoinRequestCount(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsRejectJoinRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsRejectJoinRequest(requestParameters: GroupsApiGroupsRejectJoinRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<GroupJoinRequestResponse> {
            return localVarFp.groupsRejectJoinRequest(requestParameters.requestId, requestParameters.groupJoinMessageDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsRemoveAvatarRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsRemoveAvatar(requestParameters: GroupsApiGroupsRemoveAvatarRequest, options?: RawAxiosRequestConfig): AxiosPromise<GroupResponse> {
            return localVarFp.groupsRemoveAvatar(requestParameters.groupId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsRemoveMemberRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsRemoveMember(requestParameters: GroupsApiGroupsRemoveMemberRequest, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.groupsRemoveMember(requestParameters.groupId, requestParameters.memberId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsSetAvatarRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsSetAvatar(requestParameters: GroupsApiGroupsSetAvatarRequest, options?: RawAxiosRequestConfig): AxiosPromise<GroupResponse> {
            return localVarFp.groupsSetAvatar(requestParameters.groupId, requestParameters.setGroupAvatarDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsSetMemberRoleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsSetMemberRole(requestParameters: GroupsApiGroupsSetMemberRoleRequest, options?: RawAxiosRequestConfig): AxiosPromise<GroupMemberResponse> {
            return localVarFp.groupsSetMemberRole(requestParameters.groupId, requestParameters.memberId, requestParameters.setMemberRoleDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsTransferOwnerRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsTransferOwner(requestParameters: GroupsApiGroupsTransferOwnerRequest, options?: RawAxiosRequestConfig): AxiosPromise<GroupResponse> {
            return localVarFp.groupsTransferOwner(requestParameters.groupId, requestParameters.transferOwnerDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GroupsApiGroupsUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupsUpdate(requestParameters: GroupsApiGroupsUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<GroupResponse> {
            return localVarFp.groupsUpdate(requestParameters.groupId, requestParameters.updateGroupDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for groupsAddMembers operation in GroupsApi.
 */
export interface GroupsApiGroupsAddMembersRequest {
    readonly groupId: string

    readonly addGroupMembersDto: AddGroupMembersDto
}

/**
 * Request parameters for groupsApplyToJoin operation in GroupsApi.
 */
export interface GroupsApiGroupsApplyToJoinRequest {
    readonly groupId: string

    readonly groupJoinMessageDto: GroupJoinMessageDto
}

/**
 * Request parameters for groupsApproveJoinRequest operation in GroupsApi.
 */
export interface GroupsApiGroupsApproveJoinRequestRequest {
    readonly requestId: string
}

/**
 * Request parameters for groupsCancelJoinRequest operation in GroupsApi.
 */
export interface GroupsApiGroupsCancelJoinRequestRequest {
    readonly requestId: string
}

/**
 * Request parameters for groupsCreate operation in GroupsApi.
 */
export interface GroupsApiGroupsCreateRequest {
    readonly createGroupDto: CreateGroupDto
}

/**
 * Request parameters for groupsDisband operation in GroupsApi.
 */
export interface GroupsApiGroupsDisbandRequest {
    readonly groupId: string
}

/**
 * Request parameters for groupsGet operation in GroupsApi.
 */
export interface GroupsApiGroupsGetRequest {
    readonly groupId: string
}

/**
 * Request parameters for groupsInviteMember operation in GroupsApi.
 */
export interface GroupsApiGroupsInviteMemberRequest {
    readonly groupId: string

    readonly inviteGroupMemberDto: InviteGroupMemberDto
}

/**
 * Request parameters for groupsLeave operation in GroupsApi.
 */
export interface GroupsApiGroupsLeaveRequest {
    readonly groupId: string
}

/**
 * Request parameters for groupsListActionableJoinRequests operation in GroupsApi.
 */
export interface GroupsApiGroupsListActionableJoinRequestsRequest {
    readonly before?: string

    readonly beforeId?: string
}

/**
 * Request parameters for groupsListMyJoinRequests operation in GroupsApi.
 */
export interface GroupsApiGroupsListMyJoinRequestsRequest {
    readonly before?: string

    readonly beforeId?: string
}

/**
 * Request parameters for groupsListPendingJoinRequests operation in GroupsApi.
 */
export interface GroupsApiGroupsListPendingJoinRequestsRequest {
    readonly groupId: string
}

/**
 * Request parameters for groupsMuteMember operation in GroupsApi.
 */
export interface GroupsApiGroupsMuteMemberRequest {
    readonly groupId: string

    readonly memberId: string

    readonly muteMemberDto: MuteMemberDto
}

/**
 * Request parameters for groupsRejectJoinRequest operation in GroupsApi.
 */
export interface GroupsApiGroupsRejectJoinRequestRequest {
    readonly requestId: string

    readonly groupJoinMessageDto: GroupJoinMessageDto
}

/**
 * Request parameters for groupsRemoveAvatar operation in GroupsApi.
 */
export interface GroupsApiGroupsRemoveAvatarRequest {
    readonly groupId: string
}

/**
 * Request parameters for groupsRemoveMember operation in GroupsApi.
 */
export interface GroupsApiGroupsRemoveMemberRequest {
    readonly groupId: string

    readonly memberId: string
}

/**
 * Request parameters for groupsSetAvatar operation in GroupsApi.
 */
export interface GroupsApiGroupsSetAvatarRequest {
    readonly groupId: string

    readonly setGroupAvatarDto: SetGroupAvatarDto
}

/**
 * Request parameters for groupsSetMemberRole operation in GroupsApi.
 */
export interface GroupsApiGroupsSetMemberRoleRequest {
    readonly groupId: string

    readonly memberId: string

    readonly setMemberRoleDto: SetMemberRoleDto
}

/**
 * Request parameters for groupsTransferOwner operation in GroupsApi.
 */
export interface GroupsApiGroupsTransferOwnerRequest {
    readonly groupId: string

    readonly transferOwnerDto: TransferOwnerDto
}

/**
 * Request parameters for groupsUpdate operation in GroupsApi.
 */
export interface GroupsApiGroupsUpdateRequest {
    readonly groupId: string

    readonly updateGroupDto: UpdateGroupDto
}

/**
 * GroupsApi - object-oriented interface
 */
export class GroupsApi extends BaseAPI {
    /**
     * 
     * @param {GroupsApiGroupsAddMembersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsAddMembers(requestParameters: GroupsApiGroupsAddMembersRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsAddMembers(requestParameters.groupId, requestParameters.addGroupMembersDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsApplyToJoinRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsApplyToJoin(requestParameters: GroupsApiGroupsApplyToJoinRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsApplyToJoin(requestParameters.groupId, requestParameters.groupJoinMessageDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsApproveJoinRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsApproveJoinRequest(requestParameters: GroupsApiGroupsApproveJoinRequestRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsApproveJoinRequest(requestParameters.requestId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsCancelJoinRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsCancelJoinRequest(requestParameters: GroupsApiGroupsCancelJoinRequestRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsCancelJoinRequest(requestParameters.requestId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsCreate(requestParameters: GroupsApiGroupsCreateRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsCreate(requestParameters.createGroupDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsDisbandRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsDisband(requestParameters: GroupsApiGroupsDisbandRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsDisband(requestParameters.groupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsGet(requestParameters: GroupsApiGroupsGetRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsGet(requestParameters.groupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsInviteMemberRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsInviteMember(requestParameters: GroupsApiGroupsInviteMemberRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsInviteMember(requestParameters.groupId, requestParameters.inviteGroupMemberDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsLeaveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsLeave(requestParameters: GroupsApiGroupsLeaveRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsLeave(requestParameters.groupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsList(options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsListActionableJoinRequestsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsListActionableJoinRequests(requestParameters: GroupsApiGroupsListActionableJoinRequestsRequest = {}, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsListActionableJoinRequests(requestParameters.before, requestParameters.beforeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsListMyJoinRequestsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsListMyJoinRequests(requestParameters: GroupsApiGroupsListMyJoinRequestsRequest = {}, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsListMyJoinRequests(requestParameters.before, requestParameters.beforeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsListPendingJoinRequestsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsListPendingJoinRequests(requestParameters: GroupsApiGroupsListPendingJoinRequestsRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsListPendingJoinRequests(requestParameters.groupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsMuteMemberRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsMuteMember(requestParameters: GroupsApiGroupsMuteMemberRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsMuteMember(requestParameters.groupId, requestParameters.memberId, requestParameters.muteMemberDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsPendingJoinRequestCount(options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsPendingJoinRequestCount(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsRejectJoinRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsRejectJoinRequest(requestParameters: GroupsApiGroupsRejectJoinRequestRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsRejectJoinRequest(requestParameters.requestId, requestParameters.groupJoinMessageDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsRemoveAvatarRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsRemoveAvatar(requestParameters: GroupsApiGroupsRemoveAvatarRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsRemoveAvatar(requestParameters.groupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsRemoveMemberRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsRemoveMember(requestParameters: GroupsApiGroupsRemoveMemberRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsRemoveMember(requestParameters.groupId, requestParameters.memberId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsSetAvatarRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsSetAvatar(requestParameters: GroupsApiGroupsSetAvatarRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsSetAvatar(requestParameters.groupId, requestParameters.setGroupAvatarDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsSetMemberRoleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsSetMemberRole(requestParameters: GroupsApiGroupsSetMemberRoleRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsSetMemberRole(requestParameters.groupId, requestParameters.memberId, requestParameters.setMemberRoleDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsTransferOwnerRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsTransferOwner(requestParameters: GroupsApiGroupsTransferOwnerRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsTransferOwner(requestParameters.groupId, requestParameters.transferOwnerDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GroupsApiGroupsUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public groupsUpdate(requestParameters: GroupsApiGroupsUpdateRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).groupsUpdate(requestParameters.groupId, requestParameters.updateGroupDto, options).then((request) => request(this.axios, this.basePath));
    }
}

