/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { MarkImReadDto } from '../models';
// @ts-ignore
import type { RevokeImMessageDto } from '../models';
// @ts-ignore
import type { SyncImChannelMessagesDto } from '../models';
// @ts-ignore
import type { SyncImConversationsDto } from '../models';
// @ts-ignore
import type { SyncImReceiptsDto } from '../models';
/**
 * ImSyncApi - axios parameter creator
 */
export const ImSyncApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {MarkImReadDto} markImReadDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imSyncMarkRead: async (markImReadDto: MarkImReadDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'markImReadDto' is not null or undefined
            assertParamExists('imSyncMarkRead', 'markImReadDto', markImReadDto)
            const localVarPath = `/api/v1/im/conversations/read`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(markImReadDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SyncImReceiptsDto} syncImReceiptsDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imSyncReceipts: async (syncImReceiptsDto: SyncImReceiptsDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'syncImReceiptsDto' is not null or undefined
            assertParamExists('imSyncReceipts', 'syncImReceiptsDto', syncImReceiptsDto)
            const localVarPath = `/api/v1/im/messages/receipts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(syncImReceiptsDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RevokeImMessageDto} revokeImMessageDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imSyncRevokeMessage: async (revokeImMessageDto: RevokeImMessageDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'revokeImMessageDto' is not null or undefined
            assertParamExists('imSyncRevokeMessage', 'revokeImMessageDto', revokeImMessageDto)
            const localVarPath = `/api/v1/im/messages/revoke`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(revokeImMessageDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SyncImConversationsDto} syncImConversationsDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imSyncSyncConversations: async (syncImConversationsDto: SyncImConversationsDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'syncImConversationsDto' is not null or undefined
            assertParamExists('imSyncSyncConversations', 'syncImConversationsDto', syncImConversationsDto)
            const localVarPath = `/api/v1/im/conversations/sync`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(syncImConversationsDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SyncImChannelMessagesDto} syncImChannelMessagesDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imSyncSyncMessages: async (syncImChannelMessagesDto: SyncImChannelMessagesDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'syncImChannelMessagesDto' is not null or undefined
            assertParamExists('imSyncSyncMessages', 'syncImChannelMessagesDto', syncImChannelMessagesDto)
            const localVarPath = `/api/v1/im/messages/sync`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(syncImChannelMessagesDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ImSyncApi - functional programming interface
 */
export const ImSyncApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ImSyncApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {MarkImReadDto} markImReadDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async imSyncMarkRead(markImReadDto: MarkImReadDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.imSyncMarkRead(markImReadDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ImSyncApi.imSyncMarkRead']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SyncImReceiptsDto} syncImReceiptsDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async imSyncReceipts(syncImReceiptsDto: SyncImReceiptsDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.imSyncReceipts(syncImReceiptsDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ImSyncApi.imSyncReceipts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RevokeImMessageDto} revokeImMessageDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async imSyncRevokeMessage(revokeImMessageDto: RevokeImMessageDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.imSyncRevokeMessage(revokeImMessageDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ImSyncApi.imSyncRevokeMessage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SyncImConversationsDto} syncImConversationsDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async imSyncSyncConversations(syncImConversationsDto: SyncImConversationsDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.imSyncSyncConversations(syncImConversationsDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ImSyncApi.imSyncSyncConversations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SyncImChannelMessagesDto} syncImChannelMessagesDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async imSyncSyncMessages(syncImChannelMessagesDto: SyncImChannelMessagesDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.imSyncSyncMessages(syncImChannelMessagesDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ImSyncApi.imSyncSyncMessages']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ImSyncApi - factory interface
 */
export const ImSyncApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ImSyncApiFp(configuration)
    return {
        /**
         * 
         * @param {ImSyncApiImSyncMarkReadRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imSyncMarkRead(requestParameters: ImSyncApiImSyncMarkReadRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.imSyncMarkRead(requestParameters.markImReadDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ImSyncApiImSyncReceiptsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imSyncReceipts(requestParameters: ImSyncApiImSyncReceiptsRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.imSyncReceipts(requestParameters.syncImReceiptsDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ImSyncApiImSyncRevokeMessageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imSyncRevokeMessage(requestParameters: ImSyncApiImSyncRevokeMessageRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.imSyncRevokeMessage(requestParameters.revokeImMessageDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ImSyncApiImSyncSyncConversationsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imSyncSyncConversations(requestParameters: ImSyncApiImSyncSyncConversationsRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.imSyncSyncConversations(requestParameters.syncImConversationsDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ImSyncApiImSyncSyncMessagesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imSyncSyncMessages(requestParameters: ImSyncApiImSyncSyncMessagesRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.imSyncSyncMessages(requestParameters.syncImChannelMessagesDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for imSyncMarkRead operation in ImSyncApi.
 */
export interface ImSyncApiImSyncMarkReadRequest {
    readonly markImReadDto: MarkImReadDto
}

/**
 * Request parameters for imSyncReceipts operation in ImSyncApi.
 */
export interface ImSyncApiImSyncReceiptsRequest {
    readonly syncImReceiptsDto: SyncImReceiptsDto
}

/**
 * Request parameters for imSyncRevokeMessage operation in ImSyncApi.
 */
export interface ImSyncApiImSyncRevokeMessageRequest {
    readonly revokeImMessageDto: RevokeImMessageDto
}

/**
 * Request parameters for imSyncSyncConversations operation in ImSyncApi.
 */
export interface ImSyncApiImSyncSyncConversationsRequest {
    readonly syncImConversationsDto: SyncImConversationsDto
}

/**
 * Request parameters for imSyncSyncMessages operation in ImSyncApi.
 */
export interface ImSyncApiImSyncSyncMessagesRequest {
    readonly syncImChannelMessagesDto: SyncImChannelMessagesDto
}

/**
 * ImSyncApi - object-oriented interface
 */
export class ImSyncApi extends BaseAPI {
    /**
     * 
     * @param {ImSyncApiImSyncMarkReadRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public imSyncMarkRead(requestParameters: ImSyncApiImSyncMarkReadRequest, options?: RawAxiosRequestConfig) {
        return ImSyncApiFp(this.configuration).imSyncMarkRead(requestParameters.markImReadDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ImSyncApiImSyncReceiptsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public imSyncReceipts(requestParameters: ImSyncApiImSyncReceiptsRequest, options?: RawAxiosRequestConfig) {
        return ImSyncApiFp(this.configuration).imSyncReceipts(requestParameters.syncImReceiptsDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ImSyncApiImSyncRevokeMessageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public imSyncRevokeMessage(requestParameters: ImSyncApiImSyncRevokeMessageRequest, options?: RawAxiosRequestConfig) {
        return ImSyncApiFp(this.configuration).imSyncRevokeMessage(requestParameters.revokeImMessageDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ImSyncApiImSyncSyncConversationsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public imSyncSyncConversations(requestParameters: ImSyncApiImSyncSyncConversationsRequest, options?: RawAxiosRequestConfig) {
        return ImSyncApiFp(this.configuration).imSyncSyncConversations(requestParameters.syncImConversationsDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ImSyncApiImSyncSyncMessagesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public imSyncSyncMessages(requestParameters: ImSyncApiImSyncSyncMessagesRequest, options?: RawAxiosRequestConfig) {
        return ImSyncApiFp(this.configuration).imSyncSyncMessages(requestParameters.syncImChannelMessagesDto, options).then((request) => request(this.axios, this.basePath));
    }
}

