/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
/**
 * WukongWebhookApi - axios parameter creator
 */
export const WukongWebhookApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {any} [token] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wukongWebhookReceive: async (token?: any, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/webhooks/wukongim`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (token !== undefined) {
                for (const [key, value] of Object.entries(token)) {
                    localVarQueryParameter[key] = value;
                }
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WukongWebhookApi - functional programming interface
 */
export const WukongWebhookApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WukongWebhookApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {any} [token] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wukongWebhookReceive(token?: any, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.wukongWebhookReceive(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WukongWebhookApi.wukongWebhookReceive']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WukongWebhookApi - factory interface
 */
export const WukongWebhookApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WukongWebhookApiFp(configuration)
    return {
        /**
         * 
         * @param {WukongWebhookApiWukongWebhookReceiveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wukongWebhookReceive(requestParameters: WukongWebhookApiWukongWebhookReceiveRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.wukongWebhookReceive(requestParameters.token, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for wukongWebhookReceive operation in WukongWebhookApi.
 */
export interface WukongWebhookApiWukongWebhookReceiveRequest {
    readonly token?: any
}

/**
 * WukongWebhookApi - object-oriented interface
 */
export class WukongWebhookApi extends BaseAPI {
    /**
     * 
     * @param {WukongWebhookApiWukongWebhookReceiveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public wukongWebhookReceive(requestParameters: WukongWebhookApiWukongWebhookReceiveRequest = {}, options?: RawAxiosRequestConfig) {
        return WukongWebhookApiFp(this.configuration).wukongWebhookReceive(requestParameters.token, options).then((request) => request(this.axios, this.basePath));
    }
}

