// Generated by scripts/sync-branding.mjs. Do not edit.
export const appName = "蜘蛛侠";
export const adminAppName = "蜘蛛侠管理平台";
export const tagline = "连接彼此，沟通无界";
export const primaryColor = "#e6293f";
