import { SchemaObject } from "@nestjs/swagger/dist/interfaces/open-api-spec.interface";

const id = { type: "string", format: "uuid" } as const;
const date = { type: "string", format: "date-time" } as const;
const nullableId = { ...id, nullable: true } as const;

export const apiResponseSchemas: Record<string, SchemaObject> = {
  SuccessResponse: {
    type: "object",
    required: ["success"],
    properties: {
      success: { type: "boolean" },
      revokedSessions: { type: "integer", minimum: 0 },
    },
  },
  CountResponse: {
    type: "object",
    required: ["count"],
    properties: { count: { type: "integer" } },
  },
  MessageReceiptResponse: {
    type: "object",
    required: ["messageId", "readCount", "unreadCount"],
    properties: {
      messageId: { type: "string" },
      readCount: { type: "integer", minimum: 0 },
      unreadCount: { type: "integer", minimum: 0 },
    },
  },
  ImSyncMessageResponse: {
    type: "object",
    required: [
      "channel_id",
      "channel_type",
      "message_id",
      "message_seq",
      "client_msg_no",
      "from_uid",
      "timestamp",
      "setting",
      "payload",
    ],
    properties: {
      channel_id: { type: "string" },
      channel_type: { type: "integer", minimum: 1, maximum: 2 },
      message_id: { type: "string" },
      message_seq: { type: "integer", minimum: 0 },
      client_msg_no: { type: "string" },
      from_uid: { type: "string" },
      timestamp: { type: "integer", minimum: 0 },
      setting: { type: "integer", minimum: 0 },
      payload: { type: "object", additionalProperties: true },
    },
  },
  ImSyncConversationResponse: {
    type: "object",
    required: [
      "channel_id",
      "channel_type",
      "unread",
      "timestamp",
      "last_msg_seq",
      "last_client_msg_no",
      "version",
      "recents",
    ],
    properties: {
      channel_id: { type: "string" },
      channel_type: { type: "integer", minimum: 1, maximum: 2 },
      unread: { type: "integer", minimum: 0 },
      timestamp: { type: "integer", minimum: 0 },
      last_msg_seq: { type: "integer", minimum: 0 },
      last_client_msg_no: { type: "string" },
      version: { type: "integer", minimum: 0 },
      recents: {
        type: "array",
        items: { $ref: "#/components/schemas/ImSyncMessageResponse" },
      },
    },
  },
  ImSyncMessagesResponse: {
    type: "object",
    required: ["start_message_seq", "end_message_seq", "more", "messages"],
    properties: {
      start_message_seq: { type: "integer", minimum: 0 },
      end_message_seq: { type: "integer", minimum: 0 },
      more: { type: "integer", minimum: 0 },
      messages: {
        type: "array",
        items: { $ref: "#/components/schemas/ImSyncMessageResponse" },
      },
    },
  },
  UserResponse: {
    type: "object",
    required: ["id", "username", "nickname"],
    properties: {
      id,
      username: { type: "string" },
      nickname: { type: "string" },
      avatarUrl: { type: "string", nullable: true },
      avatarFileId: nullableId,
    },
  },
  BlockedUserResponse: {
    type: "object",
    required: ["user", "createdAt"],
    properties: {
      user: { $ref: "#/components/schemas/UserResponse" },
      createdAt: date,
    },
  },
  AdminUserResponse: {
    type: "object",
    required: [
      "id",
      "username",
      "nickname",
      "status",
      "role",
      "createdAt",
      "updatedAt",
    ],
    properties: {
      id,
      username: { type: "string" },
      nickname: { type: "string" },
      avatarUrl: { type: "string", nullable: true },
      avatarFileId: nullableId,
      status: { type: "string", enum: ["ACTIVE", "SUSPENDED", "DELETED"] },
      role: { type: "string", enum: ["USER", "ADMIN"] },
      revokedSessions: { type: "integer", minimum: 0 },
      createdAt: date,
      updatedAt: date,
      deviceSessions: {
        type: "array",
        items: { type: "object", additionalProperties: true },
      },
      _count: { type: "object", additionalProperties: { type: "integer" } },
    },
  },
  AdminGroupResponse: {
    type: "object",
    required: [
      "id",
      "name",
      "ownerId",
      "memberLimit",
      "muteAll",
      "status",
      "createdAt",
      "updatedAt",
    ],
    properties: {
      id,
      name: { type: "string" },
      avatarUrl: { type: "string", nullable: true },
      avatarFileId: nullableId,
      ownerId: id,
      memberLimit: { type: "integer" },
      muteAll: { type: "boolean" },
      status: { type: "string", enum: ["ACTIVE", "DISBANDED", "SUSPENDED"] },
      createdAt: date,
      updatedAt: date,
      owner: { type: "object", additionalProperties: true },
      _count: { type: "object", additionalProperties: { type: "integer" } },
    },
  },
  AdminGroupMemberResponse: {
    type: "object",
    required: ["groupId", "userId", "role", "status", "joinedAt", "user"],
    properties: {
      groupId: id,
      userId: id,
      role: { type: "string", enum: ["OWNER", "ADMIN", "MEMBER"] },
      status: { type: "string", enum: ["ACTIVE", "LEFT", "REMOVED"] },
      nickname: { type: "string", nullable: true },
      mutedUntil: { ...date, nullable: true },
      joinedAt: date,
      user: { type: "object", additionalProperties: true },
    },
  },
  AdminUserPageResponse: {
    type: "object",
    required: ["items", "nextCursor"],
    properties: {
      items: {
        type: "array",
        items: { $ref: "#/components/schemas/AdminUserResponse" },
      },
      nextCursor: { type: "string", format: "uuid", nullable: true },
    },
  },
  AdminDeviceSessionResponse: {
    type: "object",
    required: [
      "id",
      "deviceId",
      "deviceType",
      "deviceName",
      "lastSeenAt",
      "expiresAt",
      "createdAt",
    ],
    properties: {
      id,
      deviceId: { type: "string" },
      deviceType: { type: "string", enum: ["APP", "WEB", "DESKTOP"] },
      deviceName: { type: "string" },
      ipAddress: { type: "string", nullable: true },
      userAgent: { type: "string", nullable: true },
      lastSeenAt: date,
      expiresAt: date,
      revokedAt: { ...date, nullable: true },
      createdAt: date,
    },
  },
  AdminDeviceSessionPageResponse: {
    type: "object",
    required: ["items", "nextCursor"],
    properties: {
      items: {
        type: "array",
        items: { $ref: "#/components/schemas/AdminDeviceSessionResponse" },
      },
      nextCursor: { type: "string", format: "uuid", nullable: true },
    },
  },
  AdminGroupPageResponse: {
    type: "object",
    required: ["items", "nextCursor"],
    properties: {
      items: {
        type: "array",
        items: { $ref: "#/components/schemas/AdminGroupResponse" },
      },
      nextCursor: { type: "string", format: "uuid", nullable: true },
    },
  },
  AdminGroupMemberPageResponse: {
    type: "object",
    required: ["items", "nextCursor"],
    properties: {
      items: {
        type: "array",
        items: { $ref: "#/components/schemas/AdminGroupMemberResponse" },
      },
      nextCursor: { type: "string", format: "uuid", nullable: true },
    },
  },
  AdminOverviewResponse: {
    type: "object",
    required: [
      "generatedAt",
      "users",
      "groups",
      "files",
      "calls",
      "moderation",
    ],
    properties: {
      generatedAt: date,
      users: {
        type: "object",
        required: ["total", "active", "suspended", "new24h"],
        properties: {
          total: { type: "integer" },
          active: { type: "integer" },
          suspended: { type: "integer" },
          new24h: { type: "integer" },
        },
      },
      groups: {
        type: "object",
        required: ["total", "active", "suspended"],
        properties: {
          total: { type: "integer" },
          active: { type: "integer" },
          suspended: { type: "integer" },
        },
      },
      files: {
        type: "object",
        required: ["ready", "storageBytes"],
        properties: {
          ready: { type: "integer" },
          storageBytes: { type: "string", pattern: "^[0-9]+$" },
        },
      },
      calls: {
        type: "object",
        required: ["active", "failed24h"],
        properties: {
          active: { type: "integer" },
          failed24h: { type: "integer" },
        },
      },
      moderation: {
        type: "object",
        required: [
          "pendingGroupJoinRequests",
          "pendingReports",
          "abnormalFiles",
        ],
        properties: {
          pendingGroupJoinRequests: { type: "integer" },
          pendingReports: { type: "integer" },
          abnormalFiles: { type: "integer" },
        },
      },
    },
  },
  AuditLogResponse: {
    type: "object",
    required: ["id", "action", "targetType", "targetId", "createdAt"],
    properties: {
      id,
      actorUserId: nullableId,
      action: { type: "string" },
      targetType: { type: "string" },
      targetId: { type: "string" },
      metadata: { type: "object", additionalProperties: true, nullable: true },
      createdAt: date,
      actor: { type: "object", additionalProperties: true, nullable: true },
    },
  },
  AuditLogPageResponse: {
    type: "object",
    required: ["items", "nextCursor"],
    properties: {
      items: {
        type: "array",
        items: { $ref: "#/components/schemas/AuditLogResponse" },
      },
      nextCursor: { type: "string", format: "uuid", nullable: true },
    },
  },
  AdminCallResponse: {
    type: "object",
    required: [
      "id",
      "initiatorUserId",
      "livekitRoomName",
      "type",
      "status",
      "startedAt",
      "initiator",
    ],
    properties: {
      id,
      initiatorUserId: id,
      targetUserId: nullableId,
      groupId: nullableId,
      livekitRoomName: { type: "string" },
      type: { type: "string", enum: ["AUDIO", "VIDEO"] },
      status: {
        type: "string",
        enum: [
          "INVITING",
          "RINGING",
          "ACCEPTED",
          "CONNECTED",
          "REJECTED",
          "CANCELLED",
          "MISSED",
          "ENDED",
          "FAILED",
        ],
      },
      startedAt: date,
      answeredAt: { ...date, nullable: true },
      endedAt: { ...date, nullable: true },
      endReason: { type: "string", nullable: true },
      initiator: { type: "object", additionalProperties: true },
    },
  },
  AdminCallPageResponse: {
    type: "object",
    required: ["items", "nextCursor"],
    properties: {
      items: {
        type: "array",
        items: { $ref: "#/components/schemas/AdminCallResponse" },
      },
      nextCursor: { type: "string", format: "uuid", nullable: true },
    },
  },
  AdminFileResponse: {
    type: "object",
    required: [
      "id",
      "ownerUserId",
      "originalName",
      "mimeType",
      "sizeBytes",
      "purpose",
      "scope",
      "status",
      "createdAt",
      "owner",
    ],
    properties: {
      id,
      ownerUserId: id,
      originalName: { type: "string" },
      mimeType: { type: "string" },
      sizeBytes: { type: "string", pattern: "^[0-9]+$" },
      sha256: { type: "string", nullable: true },
      purpose: { type: "string" },
      scope: { type: "string", enum: ["PRIVATE", "DIRECT", "GROUP"] },
      scopeId: nullableId,
      status: {
        type: "string",
        enum: ["PENDING", "UPLOADED", "READY", "REJECTED", "DELETED"],
      },
      thumbnailFileId: nullableId,
      createdAt: date,
      uploadedAt: { ...date, nullable: true },
      owner: { type: "object", additionalProperties: true },
    },
  },
  AdminFilePageResponse: {
    type: "object",
    required: ["items", "nextCursor"],
    properties: {
      items: {
        type: "array",
        items: { $ref: "#/components/schemas/AdminFileResponse" },
      },
      nextCursor: { type: "string", format: "uuid", nullable: true },
    },
  },
  AdminReportResponse: {
    type: "object",
    required: [
      "id",
      "reporterUserId",
      "targetUserId",
      "reason",
      "status",
      "createdAt",
      "reporter",
      "target",
    ],
    properties: {
      id,
      reporterUserId: id,
      targetUserId: id,
      reason: { type: "string" },
      details: { type: "string", nullable: true },
      status: { type: "string", enum: ["PENDING", "RESOLVED", "DISMISSED"] },
      decidedById: nullableId,
      decisionNote: { type: "string", nullable: true },
      createdAt: date,
      decidedAt: { ...date, nullable: true },
      reporter: { type: "object", additionalProperties: true },
      target: { type: "object", additionalProperties: true },
      decidedBy: { type: "object", additionalProperties: true, nullable: true },
    },
  },
  AdminReportPageResponse: {
    type: "object",
    required: ["items", "nextCursor"],
    properties: {
      items: {
        type: "array",
        items: { $ref: "#/components/schemas/AdminReportResponse" },
      },
      nextCursor: { type: "string", format: "uuid", nullable: true },
    },
  },
  JobRunResponse: {
    type: "object",
    required: ["id", "jobName", "status", "trigger", "startedAt"],
    properties: {
      id,
      jobName: { type: "string" },
      status: {
        type: "string",
        enum: ["RUNNING", "SUCCESS", "FAILED", "SKIPPED"],
      },
      trigger: { type: "string" },
      metrics: { type: "object", additionalProperties: true, nullable: true },
      error: { type: "string", nullable: true },
      startedAt: date,
      finishedAt: { ...date, nullable: true },
    },
  },
  JobRunPageResponse: {
    type: "object",
    required: ["items", "nextCursor"],
    properties: {
      items: {
        type: "array",
        items: { $ref: "#/components/schemas/JobRunResponse" },
      },
      nextCursor: { type: "string", format: "uuid", nullable: true },
    },
  },
  ImConnectionResponse: {
    type: "object",
    required: ["uid", "token", "address"],
    properties: {
      uid: id,
      token: { type: "string" },
      address: { type: "string" },
    },
  },
  AuthSessionResponse: {
    type: "object",
    required: ["accessToken", "refreshToken", "user", "im"],
    properties: {
      accessToken: { type: "string" },
      refreshToken: { type: "string" },
      user: { $ref: "#/components/schemas/UserResponse" },
      im: { $ref: "#/components/schemas/ImConnectionResponse" },
    },
  },
  DeviceSessionResponse: {
    type: "object",
    required: [
      "id",
      "deviceId",
      "deviceType",
      "deviceName",
      "lastSeenAt",
      "createdAt",
      "current",
    ],
    properties: {
      id,
      deviceId: { type: "string" },
      deviceType: { type: "string", enum: ["APP", "WEB", "DESKTOP"] },
      deviceName: { type: "string" },
      ipAddress: { type: "string", nullable: true },
      lastSeenAt: date,
      createdAt: date,
      current: { type: "boolean" },
    },
  },
  StoredFileResponse: {
    type: "object",
    required: [
      "id",
      "originalName",
      "mimeType",
      "sizeBytes",
      "purpose",
      "scope",
      "status",
    ],
    properties: {
      id,
      originalName: { type: "string" },
      mimeType: { type: "string" },
      sizeBytes: { type: "string", pattern: "^[0-9]+$" },
      purpose: { type: "string" },
      scope: { type: "string", enum: ["PRIVATE", "DIRECT", "GROUP"] },
      scopeId: nullableId,
      thumbnailFileId: nullableId,
      status: {
        type: "string",
        enum: ["PENDING", "UPLOADED", "READY", "REJECTED", "DELETED"],
      },
      uploadedAt: { ...date, nullable: true },
      createdAt: date,
    },
  },
  FileUploadResponse: {
    type: "object",
    required: ["fileId", "uploadUrl", "method", "headers", "expiresIn"],
    properties: {
      fileId: id,
      uploadUrl: { type: "string", format: "uri" },
      method: { type: "string" },
      headers: { type: "object", additionalProperties: { type: "string" } },
      expiresIn: { type: "integer" },
    },
  },
  FileUsageResponse: {
    type: "object",
    required: ["usedBytes", "quotaBytes", "remainingBytes", "fileCount"],
    properties: {
      usedBytes: { type: "string" },
      quotaBytes: { type: "string" },
      remainingBytes: { type: "string" },
      fileCount: { type: "integer" },
    },
  },
  FileDownloadResponse: {
    type: "object",
    required: ["downloadUrl", "expiresIn", "file"],
    properties: {
      downloadUrl: { type: "string", format: "uri" },
      expiresIn: { type: "integer" },
      file: { $ref: "#/components/schemas/StoredFileResponse" },
    },
  },
  GroupMemberResponse: {
    type: "object",
    required: ["groupId", "userId", "role", "status", "joinedAt"],
    properties: {
      groupId: id,
      userId: id,
      role: { type: "string", enum: ["OWNER", "ADMIN", "MEMBER"] },
      status: { type: "string", enum: ["ACTIVE", "LEFT", "REMOVED"] },
      mutedUntil: { ...date, nullable: true },
      joinedAt: date,
      user: { $ref: "#/components/schemas/UserResponse" },
    },
  },
  GroupResponse: {
    type: "object",
    required: ["id", "name", "ownerId", "memberLimit", "muteAll", "status"],
    properties: {
      id,
      name: { type: "string" },
      ownerId: id,
      avatarFileId: nullableId,
      memberLimit: { type: "integer" },
      muteAll: { type: "boolean" },
      status: { type: "string", enum: ["ACTIVE", "DISBANDED", "SUSPENDED"] },
      members: {
        type: "array",
        items: { $ref: "#/components/schemas/GroupMemberResponse" },
      },
      createdAt: date,
      updatedAt: date,
    },
  },
  GroupJoinRequestResponse: {
    type: "object",
    required: [
      "id",
      "groupId",
      "userId",
      "requestedById",
      "type",
      "status",
      "expiresAt",
      "createdAt",
    ],
    properties: {
      id,
      groupId: id,
      userId: id,
      requestedById: id,
      decidedById: nullableId,
      type: { type: "string", enum: ["APPLY", "INVITE"] },
      status: {
        type: "string",
        enum: ["PENDING", "APPROVED", "REJECTED", "CANCELLED", "EXPIRED"],
      },
      message: { type: "string", nullable: true },
      decisionNote: { type: "string", nullable: true },
      expiresAt: date,
      createdAt: date,
      decidedAt: { ...date, nullable: true },
      group: { $ref: "#/components/schemas/GroupResponse" },
      user: { $ref: "#/components/schemas/UserResponse" },
    },
  },
  CallSessionResponse: {
    type: "object",
    required: [
      "id",
      "initiatorUserId",
      "livekitRoomName",
      "type",
      "status",
      "startedAt",
    ],
    properties: {
      id,
      initiatorUserId: id,
      targetUserId: nullableId,
      groupId: nullableId,
      livekitRoomName: { type: "string" },
      type: { type: "string", enum: ["AUDIO", "VIDEO"] },
      status: {
        type: "string",
        enum: [
          "INVITING",
          "RINGING",
          "ACCEPTED",
          "CONNECTED",
          "REJECTED",
          "CANCELLED",
          "MISSED",
          "ENDED",
          "FAILED",
        ],
      },
      startedAt: date,
      answeredAt: { ...date, nullable: true },
      endedAt: { ...date, nullable: true },
      endReason: { type: "string", nullable: true },
    },
  },
  CallHistoryResponse: {
    allOf: [
      { $ref: "#/components/schemas/CallSessionResponse" },
      {
        type: "object",
        required: ["outgoing", "peer"],
        properties: {
          outgoing: { type: "boolean" },
          peer: {
            allOf: [{ $ref: "#/components/schemas/UserResponse" }],
            nullable: true,
          },
        },
      },
    ],
  },
  LiveKitTokenResponse: {
    type: "object",
    required: ["url", "token"],
    properties: { url: { type: "string" }, token: { type: "string" } },
  },
  FriendshipResponse: {
    type: "object",
    required: ["id", "requesterId", "addresseeId", "status"],
    properties: {
      id,
      requesterId: id,
      addresseeId: id,
      status: {
        type: "string",
        enum: ["PENDING", "ACCEPTED", "REJECTED", "BLOCKED"],
      },
      createdAt: date,
      updatedAt: date,
    },
  },
  FriendRequestResponse: {
    allOf: [
      { $ref: "#/components/schemas/FriendshipResponse" },
      {
        type: "object",
        required: ["requester"],
        properties: {
          requester: { $ref: "#/components/schemas/UserResponse" },
        },
      },
    ],
  },
  FriendResponse: {
    type: "object",
    required: ["friendshipId", "user", "createdAt"],
    properties: {
      friendshipId: id,
      user: { $ref: "#/components/schemas/UserResponse" },
      createdAt: date,
    },
  },
  ConversationSettingResponse: {
    type: "object",
    required: [
      "userId",
      "channelId",
      "channelType",
      "pinned",
      "muted",
      "archived",
    ],
    properties: {
      userId: id,
      channelId: { type: "string" },
      channelType: { type: "integer", minimum: 1, maximum: 2 },
      pinned: { type: "boolean" },
      muted: { type: "boolean" },
      archived: { type: "boolean" },
      createdAt: date,
      updatedAt: date,
    },
  },
  GenericObjectResponse: { type: "object", additionalProperties: true },
};

export const operationResponseSchemas: Record<
  string,
  { schema: string; array?: boolean }
> = {
  Admin_overview: { schema: "AdminOverviewResponse" },
  Admin_listUsers: { schema: "AdminUserPageResponse" },
  Admin_getUser: { schema: "AdminUserResponse" },
  Admin_listUserDevices: { schema: "AdminDeviceSessionPageResponse" },
  Admin_suspendUser: { schema: "AdminUserResponse" },
  Admin_activateUser: { schema: "AdminUserResponse" },
  Admin_setUserRole: { schema: "AdminUserResponse" },
  Admin_listGroups: { schema: "AdminGroupPageResponse" },
  Admin_getGroup: { schema: "AdminGroupResponse" },
  Admin_listGroupMembers: { schema: "AdminGroupMemberPageResponse" },
  Admin_setGroupPolicy: { schema: "AdminGroupResponse" },
  Admin_listAuditLogs: { schema: "AuditLogPageResponse" },
  Admin_listCalls: { schema: "AdminCallPageResponse" },
  Admin_listFiles: { schema: "AdminFilePageResponse" },
  Admin_listReports: { schema: "AdminReportPageResponse" },
  Admin_decideReport: { schema: "AdminReportResponse" },
  Admin_revokeUserDevice: { schema: "SuccessResponse" },
  Admin_listJobRuns: { schema: "JobRunPageResponse" },
  Admin_runCleanup: { schema: "JobRunResponse" },
  Auth_register: { schema: "AuthSessionResponse" },
  Auth_login: { schema: "AuthSessionResponse" },
  Auth_adminLogin: { schema: "AuthSessionResponse" },
  Auth_refresh: { schema: "AuthSessionResponse" },
  Auth_devices: { schema: "DeviceSessionResponse", array: true },
  Auth_revokeDevice: { schema: "SuccessResponse" },
  Auth_logout: { schema: "SuccessResponse" },
  Auth_logoutAll: { schema: "SuccessResponse" },
  Auth_changePassword: { schema: "SuccessResponse" },
  Auth_deactivateAccount: { schema: "SuccessResponse" },
  Users_getMe: { schema: "UserResponse" },
  Users_updateMe: { schema: "UserResponse" },
  Users_setAvatar: { schema: "UserResponse" },
  Users_removeAvatar: { schema: "UserResponse" },
  Users_search: { schema: "UserResponse", array: true },
  Users_getById: { schema: "UserResponse" },
  Users_report: { schema: "SuccessResponse" },
  Files_createUpload: { schema: "FileUploadResponse" },
  Files_complete: { schema: "StoredFileResponse" },
  Files_forward: { schema: "StoredFileResponse" },
  Files_download: { schema: "FileDownloadResponse" },
  Files_usage: { schema: "FileUsageResponse" },
  Files_setThumbnail: { schema: "StoredFileResponse" },
  Files_deleteFile: { schema: "SuccessResponse" },
  ImSync_markRead: { schema: "SuccessResponse" },
  ImSync_receipts: { schema: "MessageReceiptResponse", array: true },
  ImSync_revokeMessage: { schema: "SuccessResponse" },
  ImSync_syncConversations: {
    schema: "ImSyncConversationResponse",
    array: true,
  },
  ImSync_syncMessages: { schema: "ImSyncMessagesResponse" },
  Calls_create: { schema: "CallSessionResponse" },
  Calls_list: { schema: "CallHistoryResponse", array: true },
  Calls_get: { schema: "CallSessionResponse" },
  Calls_createToken: { schema: "LiveKitTokenResponse" },
  Calls_accept: { schema: "CallSessionResponse" },
  Calls_reject: { schema: "CallSessionResponse" },
  Calls_busy: { schema: "CallSessionResponse" },
  Calls_cancel: { schema: "CallSessionResponse" },
  Calls_miss: { schema: "CallSessionResponse" },
  Calls_end: { schema: "CallSessionResponse" },
  Friends_request: { schema: "FriendshipResponse" },
  Friends_accept: { schema: "FriendshipResponse" },
  Friends_reject: { schema: "FriendshipResponse" },
  Friends_listRequests: { schema: "FriendRequestResponse", array: true },
  Friends_list: { schema: "FriendResponse", array: true },
  Friends_remove: { schema: "SuccessResponse" },
  Groups_create: { schema: "GroupResponse" },
  Groups_list: { schema: "GroupResponse", array: true },
  Groups_get: { schema: "GroupResponse" },
  Groups_update: { schema: "GroupResponse" },
  Groups_addMembers: { schema: "GroupResponse" },
  Groups_setMemberRole: { schema: "GroupMemberResponse" },
  Groups_muteMember: { schema: "GroupMemberResponse" },
  Groups_transferOwner: { schema: "GroupResponse" },
  Groups_setAvatar: { schema: "GroupResponse" },
  Groups_removeAvatar: { schema: "GroupResponse" },
  Groups_applyToJoin: { schema: "GroupJoinRequestResponse" },
  Groups_inviteMember: { schema: "GroupJoinRequestResponse" },
  Groups_listMyJoinRequests: {
    schema: "GroupJoinRequestResponse",
    array: true,
  },
  Groups_listActionableJoinRequests: {
    schema: "GroupJoinRequestResponse",
    array: true,
  },
  Groups_listPendingJoinRequests: {
    schema: "GroupJoinRequestResponse",
    array: true,
  },
  Groups_pendingJoinRequestCount: { schema: "CountResponse" },
  Groups_approveJoinRequest: { schema: "GroupJoinRequestResponse" },
  Groups_rejectJoinRequest: { schema: "GroupJoinRequestResponse" },
  Groups_cancelJoinRequest: { schema: "GroupJoinRequestResponse" },
  Groups_removeMember: { schema: "SuccessResponse" },
  Groups_leave: { schema: "SuccessResponse" },
  Groups_disband: { schema: "SuccessResponse" },
  Conversations_list: { schema: "ConversationSettingResponse", array: true },
  Conversations_update: { schema: "ConversationSettingResponse" },
  Conversations_remove: { schema: "SuccessResponse" },
  Blocks_list: { schema: "BlockedUserResponse", array: true },
  Blocks_block: { schema: "BlockedUserResponse" },
  Blocks_unblock: { schema: "SuccessResponse" },
};
