/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AdminReportResponse {
    'id': string;
    'reporterUserId': string;
    'targetUserId': string;
    'reason': string;
    'details'?: string | null;
    'status': AdminReportResponseStatusEnum;
    'decidedById'?: string | null;
    'decisionNote'?: string | null;
    'createdAt': string;
    'decidedAt'?: string | null;
    'reporter': { [key: string]: any; };
    'target': { [key: string]: any; };
    'decidedBy'?: { [key: string]: any; } | null;
}

export enum AdminReportResponseStatusEnum {
    Pending = 'PENDING',
    Resolved = 'RESOLVED',
    Dismissed = 'DISMISSED'
}


