/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AdminGroupResponse {
    'id': string;
    'name': string;
    'avatarUrl'?: string | null;
    'avatarFileId'?: string | null;
    'ownerId': string;
    'memberLimit': number;
    'muteAll': boolean;
    'status': AdminGroupResponseStatusEnum;
    'createdAt': string;
    'updatedAt': string;
    'owner'?: { [key: string]: any; };
    '_count'?: { [key: string]: number; };
}

export enum AdminGroupResponseStatusEnum {
    Active = 'ACTIVE',
    Disbanded = 'DISBANDED',
    Suspended = 'SUSPENDED'
}


