/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AdminFileResponse {
    'id': string;
    'ownerUserId': string;
    'originalName': string;
    'mimeType': string;
    'sizeBytes': string;
    'sha256'?: string | null;
    'purpose': string;
    'scope': AdminFileResponseScopeEnum;
    'scopeId'?: string | null;
    'status': AdminFileResponseStatusEnum;
    'thumbnailFileId'?: string | null;
    'createdAt': string;
    'uploadedAt'?: string | null;
    'owner': { [key: string]: any; };
}

export enum AdminFileResponseScopeEnum {
    Private = 'PRIVATE',
    Direct = 'DIRECT',
    Group = 'GROUP'
}
export enum AdminFileResponseStatusEnum {
    Pending = 'PENDING',
    Uploaded = 'UPLOADED',
    Ready = 'READY',
    Rejected = 'REJECTED',
    Deleted = 'DELETED'
}


