/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdminOverviewResponseCalls } from './admin-overview-response-calls';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminOverviewResponseFiles } from './admin-overview-response-files';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminOverviewResponseGroups } from './admin-overview-response-groups';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminOverviewResponseModeration } from './admin-overview-response-moderation';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminOverviewResponseUsers } from './admin-overview-response-users';

export interface AdminOverviewResponse {
    'generatedAt': string;
    'users': AdminOverviewResponseUsers;
    'groups': AdminOverviewResponseGroups;
    'files': AdminOverviewResponseFiles;
    'calls': AdminOverviewResponseCalls;
    'moderation': AdminOverviewResponseModeration;
}

