/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AdminGroupMemberResponse {
    'groupId': string;
    'userId': string;
    'role': AdminGroupMemberResponseRoleEnum;
    'status': AdminGroupMemberResponseStatusEnum;
    'nickname'?: string | null;
    'mutedUntil'?: string | null;
    'joinedAt': string;
    'user': { [key: string]: any; };
}

export enum AdminGroupMemberResponseRoleEnum {
    Owner = 'OWNER',
    Admin = 'ADMIN',
    Member = 'MEMBER'
}
export enum AdminGroupMemberResponseStatusEnum {
    Active = 'ACTIVE',
    Left = 'LEFT',
    Removed = 'REMOVED'
}


