/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AdminCallResponse {
    'id': string;
    'initiatorUserId': string;
    'targetUserId'?: string | null;
    'groupId'?: string | null;
    'livekitRoomName': string;
    'type': AdminCallResponseTypeEnum;
    'status': AdminCallResponseStatusEnum;
    'startedAt': string;
    'answeredAt'?: string | null;
    'endedAt'?: string | null;
    'endReason'?: string | null;
    'initiator': { [key: string]: any; };
}

export enum AdminCallResponseTypeEnum {
    Audio = 'AUDIO',
    Video = 'VIDEO'
}
export enum AdminCallResponseStatusEnum {
    Inviting = 'INVITING',
    Ringing = 'RINGING',
    Accepted = 'ACCEPTED',
    Connected = 'CONNECTED',
    Rejected = 'REJECTED',
    Cancelled = 'CANCELLED',
    Missed = 'MISSED',
    Ended = 'ENDED',
    Failed = 'FAILED'
}


