/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AdminUserResponse {
    'id': string;
    'username': string;
    'nickname': string;
    'avatarUrl'?: string | null;
    'avatarFileId'?: string | null;
    'status': AdminUserResponseStatusEnum;
    'role': AdminUserResponseRoleEnum;
    'revokedSessions'?: number;
    'createdAt': string;
    'updatedAt': string;
    'deviceSessions'?: Array<{ [key: string]: any; }>;
    '_count'?: { [key: string]: number; };
}

export enum AdminUserResponseStatusEnum {
    Active = 'ACTIVE',
    Suspended = 'SUSPENDED',
    Deleted = 'DELETED'
}
export enum AdminUserResponseRoleEnum {
    User = 'USER',
    Admin = 'ADMIN'
}


