/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ConversationSettingResponse {
    'userId': string;
    'channelId': string;
    'channelType': ConversationSettingResponseChannelTypeEnum;
    'pinned': boolean;
    'muted': boolean;
    'archived': boolean;
    'createdAt'?: string;
    'updatedAt'?: string;
}

export enum ConversationSettingResponseChannelTypeEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2
}


