/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateUploadDto {
    'fileName': string;
    'mimeType': string;
    'size': number;
    'purpose': CreateUploadDtoPurposeEnum;
    'scope': CreateUploadDtoScopeEnum;
    'scopeId'?: string;
}

export enum CreateUploadDtoPurposeEnum {
    Avatar = 'AVATAR',
    ChatImage = 'CHAT_IMAGE',
    ChatVoice = 'CHAT_VOICE',
    ChatVideo = 'CHAT_VIDEO',
    ChatFile = 'CHAT_FILE'
}
export enum CreateUploadDtoScopeEnum {
    Private = 'PRIVATE',
    Direct = 'DIRECT',
    Group = 'GROUP'
}


