/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DeviceSessionResponse {
    'id': string;
    'deviceId': string;
    'deviceType': DeviceSessionResponseDeviceTypeEnum;
    'deviceName': string;
    'ipAddress'?: string | null;
    'lastSeenAt': string;
    'createdAt': string;
    'current': boolean;
}

export enum DeviceSessionResponseDeviceTypeEnum {
    App = 'APP',
    Web = 'WEB',
    Desktop = 'DESKTOP'
}


