/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GroupMemberResponse } from './group-member-response';

export interface GroupResponse {
    'id': string;
    'name': string;
    'ownerId': string;
    'avatarFileId'?: string | null;
    'memberLimit': number;
    'muteAll': boolean;
    'status': GroupResponseStatusEnum;
    'members'?: Array<GroupMemberResponse>;
    'createdAt'?: string;
    'updatedAt'?: string;
}

export enum GroupResponseStatusEnum {
    Active = 'ACTIVE',
    Disbanded = 'DISBANDED',
    Suspended = 'SUSPENDED'
}


