/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GroupResponse } from './group-response';
// May contain unused imports in some cases
// @ts-ignore
import type { UserResponse } from './user-response';

export interface GroupJoinRequestResponse {
    'id': string;
    'groupId': string;
    'userId': string;
    'requestedById': string;
    'decidedById'?: string | null;
    'type': GroupJoinRequestResponseTypeEnum;
    'status': GroupJoinRequestResponseStatusEnum;
    'message'?: string | null;
    'decisionNote'?: string | null;
    'expiresAt': string;
    'createdAt': string;
    'decidedAt'?: string | null;
    'group'?: GroupResponse;
    'user'?: UserResponse;
}

export enum GroupJoinRequestResponseTypeEnum {
    Apply = 'APPLY',
    Invite = 'INVITE'
}
export enum GroupJoinRequestResponseStatusEnum {
    Pending = 'PENDING',
    Approved = 'APPROVED',
    Rejected = 'REJECTED',
    Cancelled = 'CANCELLED',
    Expired = 'EXPIRED'
}


