/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface LoginDto {
    'username': string;
    'password': string;
    'deviceId'?: string;
    'deviceType'?: LoginDtoDeviceTypeEnum;
    'deviceName'?: string;
}

export enum LoginDtoDeviceTypeEnum {
    App = 'APP',
    Web = 'WEB',
    Desktop = 'DESKTOP'
}


