/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ServerInfoGetInfo200ResponseCapabilities } from './server-info-get-info200-response-capabilities';

export interface ServerInfoGetInfo200Response {
    'product': ServerInfoGetInfo200ResponseProductEnum;
    'apiVersion': ServerInfoGetInfo200ResponseApiVersionEnum;
    'name': string;
    'registrationEnabled': boolean;
    'capabilities': ServerInfoGetInfo200ResponseCapabilities;
    'uploadLimits': { [key: string]: number; };
}

export enum ServerInfoGetInfo200ResponseProductEnum {
    Chat = 'chat'
}
export enum ServerInfoGetInfo200ResponseApiVersionEnum {
    NUMBER_1 = 1
}


