/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface StoredFileResponse {
    'id': string;
    'originalName': string;
    'mimeType': string;
    'sizeBytes': string;
    'purpose': string;
    'scope': StoredFileResponseScopeEnum;
    'scopeId'?: string | null;
    'thumbnailFileId'?: string | null;
    'status': StoredFileResponseStatusEnum;
    'uploadedAt'?: string | null;
    'createdAt'?: string;
}

export enum StoredFileResponseScopeEnum {
    Private = 'PRIVATE',
    Direct = 'DIRECT',
    Group = 'GROUP'
}
export enum StoredFileResponseStatusEnum {
    Pending = 'PENDING',
    Uploaded = 'UPLOADED',
    Ready = 'READY',
    Rejected = 'REJECTED',
    Deleted = 'DELETED'
}


