/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ReceiptMessageDto } from './receipt-message-dto';

export interface SyncImReceiptsDto {
    'channelId': string;
    'channelType': SyncImReceiptsDtoChannelTypeEnum;
    'messages': Array<ReceiptMessageDto>;
}

export enum SyncImReceiptsDtoChannelTypeEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2
}


