/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SyncImChannelMessagesDto {
    'startMessageSeq'?: number;
    'endMessageSeq'?: number;
    'limit'?: number;
    'channelId': string;
    'channelType': SyncImChannelMessagesDtoChannelTypeEnum;
    'pullMode': SyncImChannelMessagesDtoPullModeEnum;
}

export enum SyncImChannelMessagesDtoChannelTypeEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2
}
export enum SyncImChannelMessagesDtoPullModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}


