/* tslint:disable */
/* eslint-disable */
/**
 * Chat Server API
 * Flutter chat backend powered by WuKongIM, LiveKit and S3-compatible storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateConversationSettingDto {
    'channelId': string;
    'channelType': UpdateConversationSettingDtoChannelTypeEnum;
    'pinned'?: boolean;
    'muted'?: boolean;
    'archived'?: boolean;
}

export enum UpdateConversationSettingDtoChannelTypeEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2
}


