// Generated by scripts/sync-branding.mjs. Do not edit.
abstract final class GeneratedBranding {
  static const appName = '蜘蛛侠';
  static const tagline = '连接彼此，沟通无界';
  static const primaryColorValue = 0xFFE6293F;
}
